# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_v005.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QCommandLinkButton, QFrame,
    QGridLayout, QGroupBox, QHBoxLayout, QHeaderView,
    QLabel, QLineEdit, QListView, QListWidget,
    QListWidgetItem, QMainWindow, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QToolBox,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1086, 928)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.label_19.setFont(font)

        self.gridLayout_4.addWidget(self.label_19, 1, 1, 1, 1)

        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_rank = QLabel(self.frame_3)
        self.label_rank.setObjectName(u"label_rank")
        self.label_rank.setGeometry(QRect(5, 0, 250, 21))
        font1 = QFont()
        font1.setPointSize(8)
        self.label_rank.setFont(font1)

        self.gridLayout_4.addWidget(self.frame_3, 1, 3, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer, 1, 0, 1, 1)

        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_projectname = QLabel(self.frame_2)
        self.label_projectname.setObjectName(u"label_projectname")
        self.label_projectname.setGeometry(QRect(5, 0, 151, 21))
        self.label_projectname.setFont(font1)

        self.gridLayout_4.addWidget(self.frame_2, 2, 3, 1, 1)

        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setFont(font)

        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_3, 0, 0, 1, 1)

        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setFont(font)

        self.gridLayout_4.addWidget(self.label_8, 2, 1, 1, 1)

        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_4.addItem(self.horizontalSpacer_4, 2, 0, 1, 1)

        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy1)
        self.frame.setMinimumSize(QSize(150, 0))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_username = QLabel(self.frame)
        self.label_username.setObjectName(u"label_username")
        self.label_username.setGeometry(QRect(5, 0, 300, 20))
        self.label_username.setFont(font1)

        self.gridLayout_4.addWidget(self.frame, 0, 3, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 1, 1, 1)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.pushButton_reset = QPushButton(self.centralwidget)
        self.pushButton_reset.setObjectName(u"pushButton_reset")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy2)
        self.pushButton_reset.setMinimumSize(QSize(28, 28))
        self.pushButton_reset.setMaximumSize(QSize(34, 34))
        self.pushButton_reset.setStyleSheet(u"")

        self.gridLayout_2.addWidget(self.pushButton_reset, 0, 3, 1, 1)

        self.commandLinkButton_shotgrid = QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_shotgrid.setObjectName(u"commandLinkButton_shotgrid")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.commandLinkButton_shotgrid.sizePolicy().hasHeightForWidth())
        self.commandLinkButton_shotgrid.setSizePolicy(sizePolicy3)
        self.commandLinkButton_shotgrid.setMinimumSize(QSize(30, 30))
        self.commandLinkButton_shotgrid.setMaximumSize(QSize(110, 34))
        font2 = QFont()
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        self.commandLinkButton_shotgrid.setFont(font2)
        self.commandLinkButton_shotgrid.setMouseTracking(False)
        self.commandLinkButton_shotgrid.setAutoFillBackground(False)
        self.commandLinkButton_shotgrid.setStyleSheet(u"color: rgb(211, 215, 207);\n"
"background-color: rgb(85, 87, 83);")
        self.commandLinkButton_shotgrid.setCheckable(False)
        self.commandLinkButton_shotgrid.setChecked(False)
        self.commandLinkButton_shotgrid.setAutoExclusive(False)
        self.commandLinkButton_shotgrid.setAutoDefault(False)
        self.commandLinkButton_shotgrid.setDefault(False)

        self.gridLayout_2.addWidget(self.commandLinkButton_shotgrid, 0, 2, 1, 1)

        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_2.addItem(self.horizontalSpacer_6, 0, 0, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        sizePolicy2.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy2)
        font3 = QFont()
        font3.setBold(False)
        self.label_3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.comboBox_seq = QComboBox(self.centralwidget)
        self.comboBox_seq.setObjectName(u"comboBox_seq")
        self.comboBox_seq.setMinimumSize(QSize(135, 0))

        self.horizontalLayout_2.addWidget(self.comboBox_seq)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)


        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.gridLayout_tabWidget_all = QGridLayout()
        self.gridLayout_tabWidget_all.setObjectName(u"gridLayout_tabWidget_all")
        self.tabWidget_all = QTabWidget(self.centralwidget)
        self.tabWidget_all.setObjectName(u"tabWidget_all")
        font4 = QFont()
        font4.setBold(True)
        self.tabWidget_all.setFont(font4)
        self.tabWidget_all.setStyleSheet(u"")
        self.tabWidget_all.setInputMethodHints(Qt.ImhNone)
        self.tabWidget_all.setTabPosition(QTabWidget.North)
        self.tabWidget_all.setTabShape(QTabWidget.Rounded)
        self.tabWidget_all.setUsesScrollButtons(True)
        self.tabWidget_all.setDocumentMode(False)
        self.tabWidget_all.setTabsClosable(False)
        self.tabWidget_all.setMovable(True)
        self.tabWidget_all.setTabBarAutoHide(False)
        self.tab_shot = QWidget()
        self.tab_shot.setObjectName(u"tab_shot")
        self.label_shot_filepath = QLabel(self.tab_shot)
        self.label_shot_filepath.setObjectName(u"label_shot_filepath")
        self.label_shot_filepath.setGeometry(QRect(290, 20, 521, 19))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(False)
        self.label_shot_filepath.setFont(font5)
        self.groupBox_shot_comment = QGroupBox(self.tab_shot)
        self.groupBox_shot_comment.setObjectName(u"groupBox_shot_comment")
        self.groupBox_shot_comment.setGeometry(QRect(820, 250, 231, 131))
        font6 = QFont()
        font6.setBold(True)
        font6.setUnderline(False)
        font6.setStrikeOut(False)
        self.groupBox_shot_comment.setFont(font6)
        self.groupBox_shot_comment.setFlat(False)
        self.groupBox_shot_comment.setCheckable(False)
        self.plainTextEdit_shot_comment = QPlainTextEdit(self.groupBox_shot_comment)
        self.plainTextEdit_shot_comment.setObjectName(u"plainTextEdit_shot_comment")
        self.plainTextEdit_shot_comment.setGeometry(QRect(0, 20, 231, 111))
        self.groupBox_shot_file_info = QGroupBox(self.tab_shot)
        self.groupBox_shot_file_info.setObjectName(u"groupBox_shot_file_info")
        self.groupBox_shot_file_info.setGeometry(QRect(820, 50, 231, 191))
        self.groupBox_shot_file_info.setFont(font6)
        self.groupBox_shot_file_info.setFlat(False)
        self.groupBox_shot_file_info.setCheckable(False)
        self.verticalLayoutWidget = QWidget(self.groupBox_shot_file_info)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_16 = QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName(u"label_16")
        font7 = QFont()
        font7.setPointSize(9)
        font7.setBold(False)
        font7.setUnderline(False)
        font7.setStrikeOut(False)
        self.label_16.setFont(font7)

        self.verticalLayout_3.addWidget(self.label_16)

        self.label_14 = QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font7)

        self.verticalLayout_3.addWidget(self.label_14)

        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font7)

        self.verticalLayout_3.addWidget(self.label_10)

        self.label_6 = QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font7)

        self.verticalLayout_3.addWidget(self.label_6)

        self.label_9 = QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font7)

        self.verticalLayout_3.addWidget(self.label_9)

        self.label_20 = QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setFont(font7)

        self.verticalLayout_3.addWidget(self.label_20)

        self.verticalLayoutWidget_2 = QWidget(self.groupBox_shot_file_info)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_shot_filename = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filename.setObjectName(u"label_shot_filename")
        self.label_shot_filename.setFont(font7)

        self.verticalLayout_4.addWidget(self.label_shot_filename)

        self.label_shot_filetype = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filetype.setObjectName(u"label_shot_filetype")
        self.label_shot_filetype.setFont(font7)

        self.verticalLayout_4.addWidget(self.label_shot_filetype)

        self.label_shot_framerange = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_framerange.setObjectName(u"label_shot_framerange")
        self.label_shot_framerange.setFont(font7)

        self.verticalLayout_4.addWidget(self.label_shot_framerange)

        self.label_shot_resolution = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_resolution.setObjectName(u"label_shot_resolution")
        self.label_shot_resolution.setFont(font7)

        self.verticalLayout_4.addWidget(self.label_shot_resolution)

        self.label_shot_savedtime = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_savedtime.setObjectName(u"label_shot_savedtime")
        self.label_shot_savedtime.setFont(font7)

        self.verticalLayout_4.addWidget(self.label_shot_savedtime)

        self.label_shot_filesize = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filesize.setObjectName(u"label_shot_filesize")
        self.label_shot_filesize.setFont(font7)

        self.verticalLayout_4.addWidget(self.label_shot_filesize)

        self.pushButton_shot_open = QPushButton(self.tab_shot)
        self.pushButton_shot_open.setObjectName(u"pushButton_shot_open")
        self.pushButton_shot_open.setGeometry(QRect(820, 440, 231, 41))
        self.treeWidget = QTreeWidget(self.tab_shot)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(10, 20, 271, 461))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(False)
        self.treeWidget.setFont(font8)
        self.treeWidget.setColumnCount(1)
        self.pushButton_shot_new = QPushButton(self.tab_shot)
        self.pushButton_shot_new.setObjectName(u"pushButton_shot_new")
        self.pushButton_shot_new.setGeometry(QRect(820, 390, 231, 41))
        self.tabWidget_shot_status = QTabWidget(self.tab_shot)
        self.tabWidget_shot_status.setObjectName(u"tabWidget_shot_status")
        self.tabWidget_shot_status.setGeometry(QRect(10, 490, 1039, 201))
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.tabWidget_shot_status.sizePolicy().hasHeightForWidth())
        self.tabWidget_shot_status.setSizePolicy(sizePolicy4)
        self.tabWidget_shot_status.setTabletTracking(False)
        self.tabWidget_shot_status.setUsesScrollButtons(True)
        self.tabWidget_shot_status.setDocumentMode(True)
        self.tabWidget_shot_status.setTabsClosable(False)
        self.tabWidget_shot_status.setMovable(True)
        self.tabWidget_shot_status.setTabBarAutoHide(False)
        self.tab_shot_fx = QWidget()
        self.tab_shot_fx.setObjectName(u"tab_shot_fx")
        self.tableWidget_shot_ani = QTableWidget(self.tab_shot_fx)
        self.tableWidget_shot_ani.setObjectName(u"tableWidget_shot_ani")
        self.tableWidget_shot_ani.setGeometry(QRect(0, 10, 1041, 171))
        sizePolicy3.setHeightForWidth(self.tableWidget_shot_ani.sizePolicy().hasHeightForWidth())
        self.tableWidget_shot_ani.setSizePolicy(sizePolicy3)
        self.tableWidget_shot_ani.setFont(font3)
        self.tableWidget_shot_ani.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_shot_ani.verticalHeader().setVisible(False)
        self.tabWidget_shot_status.addTab(self.tab_shot_fx, "")
        self.tab_shot_comp = QWidget()
        self.tab_shot_comp.setObjectName(u"tab_shot_comp")
        self.tableWidget_shot_cmp = QTableWidget(self.tab_shot_comp)
        self.tableWidget_shot_cmp.setObjectName(u"tableWidget_shot_cmp")
        self.tableWidget_shot_cmp.setGeometry(QRect(0, 10, 1041, 171))
        self.tableWidget_shot_cmp.setFont(font3)
        self.tableWidget_shot_cmp.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_shot_cmp.verticalHeader().setVisible(False)
        self.tabWidget_shot_status.addTab(self.tab_shot_comp, "")
        self.tab_shot_lit = QWidget()
        self.tab_shot_lit.setObjectName(u"tab_shot_lit")
        self.tableWidget_shot_lgt = QTableWidget(self.tab_shot_lit)
        self.tableWidget_shot_lgt.setObjectName(u"tableWidget_shot_lgt")
        self.tableWidget_shot_lgt.setGeometry(QRect(0, 10, 1041, 171))
        self.tableWidget_shot_lgt.setFont(font3)
        self.tableWidget_shot_lgt.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_shot_lgt.verticalHeader().setVisible(False)
        self.tabWidget_shot_status.addTab(self.tab_shot_lit, "")
        self.tab_shot_ldv = QWidget()
        self.tab_shot_ldv.setObjectName(u"tab_shot_ldv")
        self.tableWidget_shot_ly = QTableWidget(self.tab_shot_ldv)
        self.tableWidget_shot_ly.setObjectName(u"tableWidget_shot_ly")
        self.tableWidget_shot_ly.setGeometry(QRect(0, 10, 1041, 171))
        self.tableWidget_shot_ly.setFont(font3)
        self.tableWidget_shot_ly.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_shot_ly.verticalHeader().setVisible(False)
        self.tabWidget_shot_status.addTab(self.tab_shot_ldv, "")
        self.tab_shot_mm = QWidget()
        self.tab_shot_mm.setObjectName(u"tab_shot_mm")
        self.tableWidget_shot_mm = QTableWidget(self.tab_shot_mm)
        self.tableWidget_shot_mm.setObjectName(u"tableWidget_shot_mm")
        self.tableWidget_shot_mm.setGeometry(QRect(0, 10, 1041, 171))
        self.tableWidget_shot_mm.setFont(font3)
        self.tableWidget_shot_mm.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_shot_mm.verticalHeader().setVisible(False)
        self.tabWidget_shot_status.addTab(self.tab_shot_mm, "")
        self.tabWidget_shot_task = QTabWidget(self.tab_shot)
        self.tabWidget_shot_task.setObjectName(u"tabWidget_shot_task")
        self.tabWidget_shot_task.setGeometry(QRect(290, 50, 519, 429))
        self.tabWidget_shot_task.setFont(font4)
        self.tabWidget_shot_task.setMovable(False)
        self.tab_work = QWidget()
        self.tab_work.setObjectName(u"tab_work")
        self.tableWidget_shot_work = QTableWidget(self.tab_work)
        self.tableWidget_shot_work.setObjectName(u"tableWidget_shot_work")
        self.tableWidget_shot_work.setGeometry(QRect(10, 10, 496, 378))
        self.tableWidget_shot_work.setFont(font5)
        self.tableWidget_shot_work.setMouseTracking(False)
        self.tableWidget_shot_work.setStyleSheet(u"")
        self.tableWidget_shot_work.horizontalHeader().setVisible(False)
        self.tableWidget_shot_work.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_shot_work.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_shot_work.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_shot_work.horizontalHeader().setHighlightSections(False)
        self.tableWidget_shot_work.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableWidget_shot_work.verticalHeader().setVisible(False)
        self.tableWidget_shot_work.verticalHeader().setDefaultSectionSize(160)
        self.tabWidget_shot_task.addTab(self.tab_work, "")
        self.tab_exr = QWidget()
        self.tab_exr.setObjectName(u"tab_exr")
        self.tableWidget_shot_exr = QTableWidget(self.tab_exr)
        self.tableWidget_shot_exr.setObjectName(u"tableWidget_shot_exr")
        self.tableWidget_shot_exr.setGeometry(QRect(10, 10, 496, 378))
        self.tableWidget_shot_exr.setFont(font5)
        self.tableWidget_shot_exr.horizontalHeader().setVisible(False)
        self.tableWidget_shot_exr.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_shot_exr.verticalHeader().setVisible(False)
        self.tableWidget_shot_exr.verticalHeader().setDefaultSectionSize(90)
        self.tabWidget_shot_task.addTab(self.tab_exr, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tableWidget_shot_mov = QTableWidget(self.tab_5)
        self.tableWidget_shot_mov.setObjectName(u"tableWidget_shot_mov")
        self.tableWidget_shot_mov.setGeometry(QRect(10, 10, 496, 378))
        self.tableWidget_shot_mov.setFont(font5)
        self.tableWidget_shot_mov.horizontalHeader().setVisible(False)
        self.tableWidget_shot_mov.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_shot_mov.verticalHeader().setVisible(False)
        self.tableWidget_shot_mov.verticalHeader().setDefaultSectionSize(90)
        self.tabWidget_shot_task.addTab(self.tab_5, "")
        self.tab_all = QWidget()
        self.tab_all.setObjectName(u"tab_all")
        self.listWidget_shot_allfile = QListWidget(self.tab_all)
        self.listWidget_shot_allfile.setObjectName(u"listWidget_shot_allfile")
        self.listWidget_shot_allfile.setGeometry(QRect(10, 47, 496, 341))
        font9 = QFont()
        font9.setPointSize(13)
        font9.setBold(False)
        self.listWidget_shot_allfile.setFont(font9)
        self.listWidget_shot_allfile.setFrameShape(QFrame.HLine)
        self.listWidget_shot_allfile.setMidLineWidth(0)
        self.listWidget_shot_allfile.setDragEnabled(False)
        self.listWidget_shot_allfile.setDefaultDropAction(Qt.MoveAction)
        self.listWidget_shot_allfile.setMovement(QListView.Static)
        self.listWidget_shot_allfile.setProperty("isWrapping", False)
        self.listWidget_shot_allfile.setLayoutMode(QListView.SinglePass)
        self.listWidget_shot_allfile.setViewMode(QListView.ListMode)
        self.listWidget_shot_allfile.setModelColumn(0)
        self.listWidget_shot_allfile.setSortingEnabled(True)
        self.lineEdit_alllist_search = QLineEdit(self.tab_all)
        self.lineEdit_alllist_search.setObjectName(u"lineEdit_alllist_search")
        self.lineEdit_alllist_search.setGeometry(QRect(10, 10, 401, 26))
        self.lineEdit_alllist_search.setFont(font3)
        self.pushButton_search = QPushButton(self.tab_all)
        self.pushButton_search.setObjectName(u"pushButton_search")
        self.pushButton_search.setGeometry(QRect(420, 10, 84, 27))
        self.tabWidget_shot_task.addTab(self.tab_all, "")
        self.tabWidget_all.addTab(self.tab_shot, "")
        self.tab_my_task = QWidget()
        self.tab_my_task.setObjectName(u"tab_my_task")
        self.groupBox_shot_comment_2 = QGroupBox(self.tab_my_task)
        self.groupBox_shot_comment_2.setObjectName(u"groupBox_shot_comment_2")
        self.groupBox_shot_comment_2.setGeometry(QRect(820, 50, 231, 331))
        self.groupBox_shot_comment_2.setFont(font6)
        self.groupBox_shot_comment_2.setFlat(False)
        self.groupBox_shot_comment_2.setCheckable(False)
        self.plainTextEdit_mytask_comment = QPlainTextEdit(self.groupBox_shot_comment_2)
        self.plainTextEdit_mytask_comment.setObjectName(u"plainTextEdit_mytask_comment")
        self.plainTextEdit_mytask_comment.setGeometry(QRect(0, 20, 231, 311))
        self.pushButton_mytask_selectedopen = QPushButton(self.tab_my_task)
        self.pushButton_mytask_selectedopen.setObjectName(u"pushButton_mytask_selectedopen")
        self.pushButton_mytask_selectedopen.setGeometry(QRect(820, 440, 231, 41))
        self.label_mytask_filepath = QLabel(self.tab_my_task)
        self.label_mytask_filepath.setObjectName(u"label_mytask_filepath")
        self.label_mytask_filepath.setGeometry(QRect(10, 8, 521, 41))
        font10 = QFont()
        font10.setPointSize(18)
        font10.setBold(True)
        self.label_mytask_filepath.setFont(font10)
        self.pushButton_mytask_newfileopen = QPushButton(self.tab_my_task)
        self.pushButton_mytask_newfileopen.setObjectName(u"pushButton_mytask_newfileopen")
        self.pushButton_mytask_newfileopen.setGeometry(QRect(820, 390, 231, 41))
        self.tableWidget_recent_files = QTableWidget(self.tab_my_task)
        self.tableWidget_recent_files.setObjectName(u"tableWidget_recent_files")
        self.tableWidget_recent_files.setGeometry(QRect(10, 50, 500, 431))
        font11 = QFont()
        font11.setPointSize(10)
        font11.setBold(True)
        self.tableWidget_recent_files.setFont(font11)
        self.tableWidget_recent_files.horizontalHeader().setVisible(True)
        self.tableWidget_recent_files.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_recent_files.verticalHeader().setVisible(False)
        self.groupBox_mytask_thumbnail = QGroupBox(self.tab_my_task)
        self.groupBox_mytask_thumbnail.setObjectName(u"groupBox_mytask_thumbnail")
        self.groupBox_mytask_thumbnail.setGeometry(QRect(530, 50, 271, 220))
        self.groupBox_mytask_thumbnail.setFont(font6)
        self.groupBox_mytask_thumbnail.setFlat(False)
        self.groupBox_mytask_thumbnail.setCheckable(False)
        self.label_shot_comment_2 = QLabel(self.groupBox_mytask_thumbnail)
        self.label_shot_comment_2.setObjectName(u"label_shot_comment_2")
        self.label_shot_comment_2.setGeometry(QRect(10, 30, 211, 141))
        self.label_mytask_thumbnail = QLabel(self.groupBox_mytask_thumbnail)
        self.label_mytask_thumbnail.setObjectName(u"label_mytask_thumbnail")
        self.label_mytask_thumbnail.setGeometry(QRect(10, 20, 257, 201))
        self.groupBox_mytask_file_info = QGroupBox(self.tab_my_task)
        self.groupBox_mytask_file_info.setObjectName(u"groupBox_mytask_file_info")
        self.groupBox_mytask_file_info.setGeometry(QRect(530, 290, 271, 191))
        self.groupBox_mytask_file_info.setFont(font6)
        self.groupBox_mytask_file_info.setFlat(False)
        self.groupBox_mytask_file_info.setCheckable(False)
        self.verticalLayoutWidget_3 = QWidget(self.groupBox_mytask_file_info)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setFont(font7)

        self.verticalLayout_5.addWidget(self.label_17)

        self.label_15 = QLabel(self.verticalLayoutWidget_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setFont(font7)

        self.verticalLayout_5.addWidget(self.label_15)

        self.label_12 = QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font7)

        self.verticalLayout_5.addWidget(self.label_12)

        self.label_13 = QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font7)

        self.verticalLayout_5.addWidget(self.label_13)

        self.label_21 = QLabel(self.verticalLayoutWidget_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setFont(font7)

        self.verticalLayout_5.addWidget(self.label_21)

        self.verticalLayoutWidget_4 = QWidget(self.groupBox_mytask_file_info)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(90, 30, 171, 151))
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_mytask_filename = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_filename.setObjectName(u"label_mytask_filename")
        self.label_mytask_filename.setFont(font7)

        self.verticalLayout_6.addWidget(self.label_mytask_filename)

        self.label_mytask_filetype = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_filetype.setObjectName(u"label_mytask_filetype")
        self.label_mytask_filetype.setFont(font7)

        self.verticalLayout_6.addWidget(self.label_mytask_filetype)

        self.label_mytask_resolution = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_resolution.setObjectName(u"label_mytask_resolution")
        self.label_mytask_resolution.setFont(font7)

        self.verticalLayout_6.addWidget(self.label_mytask_resolution)

        self.label_mytask_savedtime = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_savedtime.setObjectName(u"label_mytask_savedtime")
        self.label_mytask_savedtime.setFont(font7)

        self.verticalLayout_6.addWidget(self.label_mytask_savedtime)

        self.label_mytask_filesize = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_filesize.setObjectName(u"label_mytask_filesize")
        self.label_mytask_filesize.setFont(font7)

        self.verticalLayout_6.addWidget(self.label_mytask_filesize)

        self.label = QLabel(self.tab_my_task)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 481, 1039, 41))
        font12 = QFont()
        font12.setPointSize(13)
        font12.setBold(True)
        self.label.setFont(font12)
        self.tableWidget_mytask_status = QTableWidget(self.tab_my_task)
        self.tableWidget_mytask_status.setObjectName(u"tableWidget_mytask_status")
        self.tableWidget_mytask_status.setGeometry(QRect(10, 520, 1039, 179))
        sizePolicy4.setHeightForWidth(self.tableWidget_mytask_status.sizePolicy().hasHeightForWidth())
        self.tableWidget_mytask_status.setSizePolicy(sizePolicy4)
        self.tableWidget_mytask_status.setFont(font3)
        self.tableWidget_mytask_status.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_mytask_status.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_mytask_status.verticalHeader().setVisible(False)
        self.tabWidget_all.addTab(self.tab_my_task, "")
        self.tab_clip = QWidget()
        self.tab_clip.setObjectName(u"tab_clip")
        self.tabWidget_template = QTabWidget(self.tab_clip)
        self.tabWidget_template.setObjectName(u"tabWidget_template")
        self.tabWidget_template.setGeometry(QRect(10, 10, 1049, 711))
        self.tabWidget_template.setFont(font4)
        self.tab_asset = QWidget()
        self.tab_asset.setObjectName(u"tab_asset")
        self.groupBox_asset_comment = QGroupBox(self.tab_asset)
        self.groupBox_asset_comment.setObjectName(u"groupBox_asset_comment")
        self.groupBox_asset_comment.setGeometry(QRect(810, 230, 227, 181))
        self.groupBox_asset_comment.setFont(font6)
        self.groupBox_asset_comment.setFlat(False)
        self.groupBox_asset_comment.setCheckable(False)
        self.label_asset_comment = QLabel(self.groupBox_asset_comment)
        self.label_asset_comment.setObjectName(u"label_asset_comment")
        self.label_asset_comment.setGeometry(QRect(10, 30, 211, 141))
        self.plainTextEdit_clip_comment_2 = QPlainTextEdit(self.groupBox_asset_comment)
        self.plainTextEdit_clip_comment_2.setObjectName(u"plainTextEdit_clip_comment_2")
        self.plainTextEdit_clip_comment_2.setGeometry(QRect(10, 30, 208, 141))
        self.groupBox_asset_file_info = QGroupBox(self.tab_asset)
        self.groupBox_asset_file_info.setObjectName(u"groupBox_asset_file_info")
        self.groupBox_asset_file_info.setGeometry(QRect(810, 30, 227, 191))
        self.groupBox_asset_file_info.setFont(font6)
        self.groupBox_asset_file_info.setFlat(False)
        self.groupBox_asset_file_info.setCheckable(False)
        self.verticalLayoutWidget_6 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_8 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_asset_filename = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filename.setObjectName(u"label_asset_filename")
        self.label_asset_filename.setFont(font7)

        self.verticalLayout_8.addWidget(self.label_asset_filename)

        self.label_asset_filetype = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filetype.setObjectName(u"label_asset_filetype")
        self.label_asset_filetype.setFont(font7)

        self.verticalLayout_8.addWidget(self.label_asset_filetype)

        self.label_asset_asset_type = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_asset_type.setObjectName(u"label_asset_asset_type")
        self.label_asset_asset_type.setFont(font7)

        self.verticalLayout_8.addWidget(self.label_asset_asset_type)

        self.label_asset_version = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_version.setObjectName(u"label_asset_version")
        self.label_asset_version.setFont(font7)

        self.verticalLayout_8.addWidget(self.label_asset_version)

        self.label_asset_savedtime = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_savedtime.setObjectName(u"label_asset_savedtime")
        self.label_asset_savedtime.setFont(font7)

        self.verticalLayout_8.addWidget(self.label_asset_savedtime)

        self.label_asset_filesize = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filesize.setObjectName(u"label_asset_filesize")
        self.label_asset_filesize.setFont(font7)

        self.verticalLayout_8.addWidget(self.label_asset_filesize)

        self.line = QFrame(self.groupBox_asset_file_info)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 175, 231, 31))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.verticalLayoutWidget_15 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_15.setObjectName(u"verticalLayoutWidget_15")
        self.verticalLayoutWidget_15.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_17 = QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.label_57 = QLabel(self.verticalLayoutWidget_15)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setFont(font7)

        self.verticalLayout_17.addWidget(self.label_57)

        self.label_58 = QLabel(self.verticalLayoutWidget_15)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setFont(font7)

        self.verticalLayout_17.addWidget(self.label_58)

        self.label_59 = QLabel(self.verticalLayoutWidget_15)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setFont(font7)

        self.verticalLayout_17.addWidget(self.label_59)

        self.label_60 = QLabel(self.verticalLayoutWidget_15)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setFont(font7)

        self.verticalLayout_17.addWidget(self.label_60)

        self.label_61 = QLabel(self.verticalLayoutWidget_15)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setFont(font7)

        self.verticalLayout_17.addWidget(self.label_61)

        self.label_62 = QLabel(self.verticalLayoutWidget_15)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setFont(font7)

        self.verticalLayout_17.addWidget(self.label_62)

        self.label_asset_filesize_2 = QLabel(self.groupBox_asset_file_info)
        self.label_asset_filesize_2.setObjectName(u"label_asset_filesize_2")
        self.label_asset_filesize_2.setGeometry(QRect(200, 190, 129, 25))
        self.label_asset_filesize_2.setFont(font7)
        self.toolBox_asset_task = QToolBox(self.tab_asset)
        self.toolBox_asset_task.setObjectName(u"toolBox_asset_task")
        self.toolBox_asset_task.setGeometry(QRect(10, 57, 791, 611))
        self.toolBox_asset_task.setFont(font4)
        self.page_mod = QWidget()
        self.page_mod.setObjectName(u"page_mod")
        self.page_mod.setGeometry(QRect(0, 0, 791, 545))
        self.listWidget_mod = QListWidget(self.page_mod)
        self.listWidget_mod.setObjectName(u"listWidget_mod")
        self.listWidget_mod.setGeometry(QRect(0, 0, 231, 545))
        self.listWidget_mod.setFont(font3)
        self.gridLayoutWidget_6 = QWidget(self.page_mod)
        self.gridLayoutWidget_6.setObjectName(u"gridLayoutWidget_6")
        self.gridLayoutWidget_6.setGeometry(QRect(240, 0, 551, 541))
        self.gridLayout_mod = QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_mod.setObjectName(u"gridLayout_mod")
        self.gridLayout_mod.setContentsMargins(0, 0, 0, 0)
        self.toolBox_asset_task.addItem(self.page_mod, u"MOD")
        self.page_rig = QWidget()
        self.page_rig.setObjectName(u"page_rig")
        self.page_rig.setGeometry(QRect(0, 0, 791, 545))
        self.listWidget_rig = QListWidget(self.page_rig)
        self.listWidget_rig.setObjectName(u"listWidget_rig")
        self.listWidget_rig.setGeometry(QRect(0, 0, 231, 545))
        self.listWidget_rig.setFont(font3)
        self.gridLayoutWidget_7 = QWidget(self.page_rig)
        self.gridLayoutWidget_7.setObjectName(u"gridLayoutWidget_7")
        self.gridLayoutWidget_7.setGeometry(QRect(240, 0, 551, 541))
        self.gridLayout_rig = QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_rig.setObjectName(u"gridLayout_rig")
        self.gridLayout_rig.setContentsMargins(0, 0, 0, 0)
        self.toolBox_asset_task.addItem(self.page_rig, u"RIG")
        self.horizontalLayoutWidget_3 = QWidget(self.tab_asset)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 0, 291, 61))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(u"label_4")
        sizePolicy2.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy2)
        self.label_4.setFont(font3)

        self.horizontalLayout_3.addWidget(self.label_4)

        self.comboBox_asset_type = QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox_asset_type.setObjectName(u"comboBox_asset_type")
        self.comboBox_asset_type.setFont(font3)

        self.horizontalLayout_3.addWidget(self.comboBox_asset_type)

        self.tabWidget_template.addTab(self.tab_asset, "")
        self.tab_clip_2 = QWidget()
        self.tab_clip_2.setObjectName(u"tab_clip_2")
        self.groupBox_asset_file_info_2 = QGroupBox(self.tab_clip_2)
        self.groupBox_asset_file_info_2.setObjectName(u"groupBox_asset_file_info_2")
        self.groupBox_asset_file_info_2.setGeometry(QRect(810, 30, 227, 191))
        self.groupBox_asset_file_info_2.setFont(font6)
        self.groupBox_asset_file_info_2.setFlat(False)
        self.groupBox_asset_file_info_2.setCheckable(False)
        self.verticalLayoutWidget_13 = QWidget(self.groupBox_asset_file_info_2)
        self.verticalLayoutWidget_13.setObjectName(u"verticalLayoutWidget_13")
        self.verticalLayoutWidget_13.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_15 = QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.label_51 = QLabel(self.verticalLayoutWidget_13)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setFont(font7)

        self.verticalLayout_15.addWidget(self.label_51)

        self.label_52 = QLabel(self.verticalLayoutWidget_13)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setFont(font7)

        self.verticalLayout_15.addWidget(self.label_52)

        self.label_53 = QLabel(self.verticalLayoutWidget_13)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setFont(font7)

        self.verticalLayout_15.addWidget(self.label_53)

        self.label_54 = QLabel(self.verticalLayoutWidget_13)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setFont(font7)

        self.verticalLayout_15.addWidget(self.label_54)

        self.label_55 = QLabel(self.verticalLayoutWidget_13)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setFont(font7)

        self.verticalLayout_15.addWidget(self.label_55)

        self.label_56 = QLabel(self.verticalLayoutWidget_13)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setFont(font7)

        self.verticalLayout_15.addWidget(self.label_56)

        self.verticalLayoutWidget_14 = QWidget(self.groupBox_asset_file_info_2)
        self.verticalLayoutWidget_14.setObjectName(u"verticalLayoutWidget_14")
        self.verticalLayoutWidget_14.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_16 = QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.label_clip_filename = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filename.setObjectName(u"label_clip_filename")
        self.label_clip_filename.setFont(font7)

        self.verticalLayout_16.addWidget(self.label_clip_filename)

        self.label_clip_filetype = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filetype.setObjectName(u"label_clip_filetype")
        self.label_clip_filetype.setFont(font7)

        self.verticalLayout_16.addWidget(self.label_clip_filetype)

        self.label_clip_framerange = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_framerange.setObjectName(u"label_clip_framerange")
        self.label_clip_framerange.setFont(font7)

        self.verticalLayout_16.addWidget(self.label_clip_framerange)

        self.label_clip_resolution = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_resolution.setObjectName(u"label_clip_resolution")
        self.label_clip_resolution.setFont(font7)

        self.verticalLayout_16.addWidget(self.label_clip_resolution)

        self.label_clip_savedtime = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_savedtime.setObjectName(u"label_clip_savedtime")
        self.label_clip_savedtime.setFont(font7)

        self.verticalLayout_16.addWidget(self.label_clip_savedtime)

        self.label_clip_filesize = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filesize.setObjectName(u"label_clip_filesize")
        self.label_clip_filesize.setFont(font7)

        self.verticalLayout_16.addWidget(self.label_clip_filesize)

        self.gridLayoutWidget_5 = QWidget(self.tab_clip_2)
        self.gridLayoutWidget_5.setObjectName(u"gridLayoutWidget_5")
        self.gridLayoutWidget_5.setGeometry(QRect(10, 10, 791, 651))
        self.gridLayout_clip = QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_clip.setObjectName(u"gridLayout_clip")
        self.gridLayout_clip.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_template.addTab(self.tab_clip_2, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayoutWidget_2 = QWidget(self.tab)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 40, 1021, 631))
        self.gridLayout_clip_fav = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_clip_fav.setObjectName(u"gridLayout_clip_fav")
        self.gridLayout_clip_fav.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 8, 141, 31))
        font13 = QFont()
        font13.setPointSize(12)
        font13.setBold(True)
        self.label_2.setFont(font13)
        self.tabWidget_template.addTab(self.tab, "")
        self.tabWidget_all.addTab(self.tab_clip, "")
        self.tab_pub = QWidget()
        self.tab_pub.setObjectName(u"tab_pub")
        self.groupBox_shot_file_info_3 = QGroupBox(self.tab_pub)
        self.groupBox_shot_file_info_3.setObjectName(u"groupBox_shot_file_info_3")
        self.groupBox_shot_file_info_3.setGeometry(QRect(780, 470, 271, 191))
        self.groupBox_shot_file_info_3.setFont(font6)
        self.groupBox_shot_file_info_3.setFlat(False)
        self.groupBox_shot_file_info_3.setCheckable(False)
        self.verticalLayoutWidget_9 = QWidget(self.groupBox_shot_file_info_3)
        self.verticalLayoutWidget_9.setObjectName(u"verticalLayoutWidget_9")
        self.verticalLayoutWidget_9.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_11 = QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_34 = QLabel(self.verticalLayoutWidget_9)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setFont(font7)

        self.verticalLayout_11.addWidget(self.label_34)

        self.label_35 = QLabel(self.verticalLayoutWidget_9)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setFont(font7)

        self.verticalLayout_11.addWidget(self.label_35)

        self.label_36 = QLabel(self.verticalLayoutWidget_9)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setFont(font7)

        self.verticalLayout_11.addWidget(self.label_36)

        self.label_37 = QLabel(self.verticalLayoutWidget_9)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setFont(font7)

        self.verticalLayout_11.addWidget(self.label_37)

        self.label_38 = QLabel(self.verticalLayoutWidget_9)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setFont(font7)

        self.verticalLayout_11.addWidget(self.label_38)

        self.label_39 = QLabel(self.verticalLayoutWidget_9)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setFont(font7)

        self.verticalLayout_11.addWidget(self.label_39)

        self.verticalLayoutWidget_10 = QWidget(self.groupBox_shot_file_info_3)
        self.verticalLayoutWidget_10.setObjectName(u"verticalLayoutWidget_10")
        self.verticalLayoutWidget_10.setGeometry(QRect(90, 30, 171, 151))
        self.verticalLayout_12 = QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.label_pub_filename = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_filename.setObjectName(u"label_pub_filename")
        self.label_pub_filename.setFont(font7)

        self.verticalLayout_12.addWidget(self.label_pub_filename)

        self.label_pub_filetype = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_filetype.setObjectName(u"label_pub_filetype")
        self.label_pub_filetype.setFont(font7)

        self.verticalLayout_12.addWidget(self.label_pub_filetype)

        self.label_pub_framerange = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_framerange.setObjectName(u"label_pub_framerange")
        self.label_pub_framerange.setFont(font7)

        self.verticalLayout_12.addWidget(self.label_pub_framerange)

        self.label_pub_resolution = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_resolution.setObjectName(u"label_pub_resolution")
        self.label_pub_resolution.setFont(font7)

        self.verticalLayout_12.addWidget(self.label_pub_resolution)

        self.label_pub_savedtime = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_savedtime.setObjectName(u"label_pub_savedtime")
        self.label_pub_savedtime.setFont(font7)

        self.verticalLayout_12.addWidget(self.label_pub_savedtime)

        self.label_pub_filesize = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_filesize.setObjectName(u"label_pub_filesize")
        self.label_pub_filesize.setFont(font7)

        self.verticalLayout_12.addWidget(self.label_pub_filesize)

        self.pushButton_pub_publish = QPushButton(self.tab_pub)
        self.pushButton_pub_publish.setObjectName(u"pushButton_pub_publish")
        self.pushButton_pub_publish.setGeometry(QRect(920, 670, 131, 41))
        self.groupBox_shot_comment_4 = QGroupBox(self.tab_pub)
        self.groupBox_shot_comment_4.setObjectName(u"groupBox_shot_comment_4")
        self.groupBox_shot_comment_4.setGeometry(QRect(420, 470, 341, 241))
        self.groupBox_shot_comment_4.setFont(font6)
        self.groupBox_shot_comment_4.setFlat(False)
        self.groupBox_shot_comment_4.setCheckable(False)
        self.plainTextEdit_pub_comment = QPlainTextEdit(self.groupBox_shot_comment_4)
        self.plainTextEdit_pub_comment.setObjectName(u"plainTextEdit_pub_comment")
        self.plainTextEdit_pub_comment.setGeometry(QRect(0, 20, 341, 221))
        self.groupBox_shot_comment_5 = QGroupBox(self.tab_pub)
        self.groupBox_shot_comment_5.setObjectName(u"groupBox_shot_comment_5")
        self.groupBox_shot_comment_5.setGeometry(QRect(420, 50, 631, 411))
        self.groupBox_shot_comment_5.setFont(font6)
        self.groupBox_shot_comment_5.setFlat(False)
        self.groupBox_shot_comment_5.setCheckable(False)
        self.label_shot_comment_4 = QLabel(self.groupBox_shot_comment_5)
        self.label_shot_comment_4.setObjectName(u"label_shot_comment_4")
        self.label_shot_comment_4.setGeometry(QRect(10, 30, 211, 141))
        self.label_pub_thumbnail = QLabel(self.groupBox_shot_comment_5)
        self.label_pub_thumbnail.setObjectName(u"label_pub_thumbnail")
        self.label_pub_thumbnail.setGeometry(QRect(0, 20, 631, 391))
        self.label_mytask_filepath_2 = QLabel(self.tab_pub)
        self.label_mytask_filepath_2.setObjectName(u"label_mytask_filepath_2")
        self.label_mytask_filepath_2.setGeometry(QRect(11, 8, 521, 61))
        self.label_mytask_filepath_2.setFont(font10)
        self.treeWidget_pub_list = QTreeWidget(self.tab_pub)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidget_pub_list.setHeaderItem(__qtreewidgetitem1)
        self.treeWidget_pub_list.setObjectName(u"treeWidget_pub_list")
        self.treeWidget_pub_list.setGeometry(QRect(10, 70, 391, 641))
        self.treeWidget_pub_list.setFont(font11)
        self.treeWidget_pub_list.header().setVisible(False)
        self.pushButton_pub_retake = QPushButton(self.tab_pub)
        self.pushButton_pub_retake.setObjectName(u"pushButton_pub_retake")
        self.pushButton_pub_retake.setGeometry(QRect(780, 670, 131, 41))
        self.tabWidget_all.addTab(self.tab_pub, "")

        self.gridLayout_tabWidget_all.addWidget(self.tabWidget_all, 0, 0, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_tabWidget_all, 3, 0, 1, 2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1086, 27))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget_all.setCurrentIndex(0)
        self.tabWidget_shot_status.setCurrentIndex(2)
        self.tabWidget_shot_task.setCurrentIndex(3)
        self.tabWidget_template.setCurrentIndex(0)
        self.toolBox_asset_task.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Rank", None))
        self.label_rank.setText("")
        self.label_projectname.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"User Name", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Project Name", None))
        self.label_username.setText("")
        self.pushButton_reset.setText("")
        self.commandLinkButton_shotgrid.setText(QCoreApplication.translate("MainWindow", u" Shotgird", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"  SEQ ", None))
        self.label_shot_filepath.setText("")
        self.groupBox_shot_comment.setTitle(QCoreApplication.translate("MainWindow", u"Comment", None))
        self.groupBox_shot_file_info.setTitle(QCoreApplication.translate("MainWindow", u"File information", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"File type", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Frame Range ", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Saved time", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"File size", None))
        self.label_shot_filename.setText("")
        self.label_shot_filetype.setText("")
        self.label_shot_framerange.setText("")
        self.label_shot_resolution.setText("")
        self.label_shot_savedtime.setText("")
        self.label_shot_filesize.setText("")
        self.pushButton_shot_open.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.pushButton_shot_new.setText(QCoreApplication.translate("MainWindow", u"NEW", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_fx), QCoreApplication.translate("MainWindow", u"ANI", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_comp), QCoreApplication.translate("MainWindow", u"COMP", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_lit), QCoreApplication.translate("MainWindow", u"LGT", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_ldv), QCoreApplication.translate("MainWindow", u"LY", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_mm), QCoreApplication.translate("MainWindow", u"MM", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_work), QCoreApplication.translate("MainWindow", u"WORK", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_exr), QCoreApplication.translate("MainWindow", u"EXR", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"MOV", None))
        self.pushButton_search.setText(QCoreApplication.translate("MainWindow", u"search", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_all), QCoreApplication.translate("MainWindow", u"ALL", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_shot), QCoreApplication.translate("MainWindow", u"SHOT", None))
        self.groupBox_shot_comment_2.setTitle(QCoreApplication.translate("MainWindow", u"Comment", None))
        self.plainTextEdit_mytask_comment.setPlainText("")
        self.pushButton_mytask_selectedopen.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.label_mytask_filepath.setText(QCoreApplication.translate("MainWindow", u"RECENT", None))
        self.pushButton_mytask_newfileopen.setText(QCoreApplication.translate("MainWindow", u"NEW", None))
        self.groupBox_mytask_thumbnail.setTitle(QCoreApplication.translate("MainWindow", u"Thumbnail", None))
        self.label_shot_comment_2.setText("")
        self.label_mytask_thumbnail.setText("")
        self.groupBox_mytask_file_info.setTitle(QCoreApplication.translate("MainWindow", u"File information", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"File type", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Saved time", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"File size", None))
        self.label_mytask_filename.setText("")
        self.label_mytask_filetype.setText("")
        self.label_mytask_resolution.setText("")
        self.label_mytask_savedtime.setText("")
        self.label_mytask_filesize.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"My Team Status", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_my_task), QCoreApplication.translate("MainWindow", u"MY TASK", None))
        self.groupBox_asset_comment.setTitle(QCoreApplication.translate("MainWindow", u" Comment", None))
        self.label_asset_comment.setText("")
        self.groupBox_asset_file_info.setTitle(QCoreApplication.translate("MainWindow", u" Asset information", None))
        self.label_asset_filename.setText("")
        self.label_asset_filetype.setText("")
        self.label_asset_asset_type.setText("")
        self.label_asset_version.setText("")
        self.label_asset_savedtime.setText("")
        self.label_asset_filesize.setText("")
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"File type", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"Asset type", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Version", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Saved time", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"File size", None))
        self.label_asset_filesize_2.setText("")
        self.toolBox_asset_task.setItemText(self.toolBox_asset_task.indexOf(self.page_mod), QCoreApplication.translate("MainWindow", u"MOD", None))
        self.toolBox_asset_task.setItemText(self.toolBox_asset_task.indexOf(self.page_rig), QCoreApplication.translate("MainWindow", u"RIG", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u" Asset type", None))
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_asset), QCoreApplication.translate("MainWindow", u"ASSET (cache)", None))
        self.groupBox_asset_file_info_2.setTitle(QCoreApplication.translate("MainWindow", u" Clip information", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"File type", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"Frame Range ", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"Saved time", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"File size", None))
        self.label_clip_filename.setText("")
        self.label_clip_filetype.setText("")
        self.label_clip_framerange.setText("")
        self.label_clip_resolution.setText("")
        self.label_clip_savedtime.setText("")
        self.label_clip_filesize.setText("")
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_clip_2), QCoreApplication.translate("MainWindow", u"CLIP", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u2605 Clip Favorites", None))
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u2605", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_clip), QCoreApplication.translate("MainWindow", u"LIB", None))
        self.groupBox_shot_file_info_3.setTitle(QCoreApplication.translate("MainWindow", u"File information", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Name", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"File type", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Frame Range ", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Saved time", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"File size", None))
        self.label_pub_filename.setText("")
        self.label_pub_filetype.setText("")
        self.label_pub_framerange.setText("")
        self.label_pub_resolution.setText("")
        self.label_pub_savedtime.setText("")
        self.label_pub_filesize.setText("")
        self.pushButton_pub_publish.setText(QCoreApplication.translate("MainWindow", u"Publish", None))
        self.groupBox_shot_comment_4.setTitle(QCoreApplication.translate("MainWindow", u"Comment", None))
        self.plainTextEdit_pub_comment.setPlainText("")
        self.groupBox_shot_comment_5.setTitle(QCoreApplication.translate("MainWindow", u"Thumbnail", None))
        self.label_shot_comment_4.setText("")
        self.label_pub_thumbnail.setText("")
        self.label_mytask_filepath_2.setText(QCoreApplication.translate("MainWindow", u"PUBLISH (Manager)", None))
        self.pushButton_pub_retake.setText(QCoreApplication.translate("MainWindow", u"Retake", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_pub), QCoreApplication.translate("MainWindow", u"PUB", None))
    # retranslateUi

