# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window_v002.ui'
##
## Created by: Qt User Interface Compiler version 6.2.4
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QListView, QListWidget, QListWidgetItem,
    QPlainTextEdit, QPushButton, QSizePolicy, QTabWidget,
    QTableWidget, QTableWidgetItem, QToolBox, QTreeWidget,
    QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1155, 889)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.tabWidget_all = QTabWidget(Form)
        self.tabWidget_all.setObjectName(u"tabWidget_all")
        self.tabWidget_all.setGeometry(QRect(40, 90, 1071, 761))
        font = QFont()
        font.setBold(True)
        self.tabWidget_all.setFont(font)
        self.tabWidget_all.setStyleSheet(u"")
        self.tabWidget_all.setInputMethodHints(Qt.ImhNone)
        self.tabWidget_all.setTabPosition(QTabWidget.North)
        self.tabWidget_all.setTabShape(QTabWidget.Rounded)
        self.tabWidget_all.setUsesScrollButtons(True)
        self.tabWidget_all.setDocumentMode(False)
        self.tabWidget_all.setTabsClosable(False)
        self.tabWidget_all.setMovable(True)
        self.tabWidget_all.setTabBarAutoHide(False)
        self.tab_shot = QWidget()
        self.tab_shot.setObjectName(u"tab_shot")
        self.gridLayoutWidget = QWidget(self.tab_shot)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(290, 50, 521, 431))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_shot_task = QTabWidget(self.gridLayoutWidget)
        self.tabWidget_shot_task.setObjectName(u"tabWidget_shot_task")
        self.tabWidget_shot_task.setFont(font)
        self.tabWidget_shot_task.setMovable(False)
        self.tab_work = QWidget()
        self.tab_work.setObjectName(u"tab_work")
        self.tableWidget_shot_work = QTableWidget(self.tab_work)
        self.tableWidget_shot_work.setObjectName(u"tableWidget_shot_work")
        self.tableWidget_shot_work.setGeometry(QRect(10, 10, 496, 378))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setBold(False)
        self.tableWidget_shot_work.setFont(font1)
        self.tableWidget_shot_work.setMouseTracking(False)
        self.tableWidget_shot_work.setStyleSheet(u"")
        self.tableWidget_shot_work.horizontalHeader().setVisible(False)
        self.tableWidget_shot_work.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_shot_work.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget_shot_work.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_shot_work.horizontalHeader().setHighlightSections(False)
        self.tableWidget_shot_work.horizontalHeader().setProperty("showSortIndicator", False)
        self.tableWidget_shot_work.verticalHeader().setVisible(False)
        self.tableWidget_shot_work.verticalHeader().setDefaultSectionSize(160)
        self.tabWidget_shot_task.addTab(self.tab_work, "")
        self.tab_exr = QWidget()
        self.tab_exr.setObjectName(u"tab_exr")
        self.tableWidget_shot_exr = QTableWidget(self.tab_exr)
        self.tableWidget_shot_exr.setObjectName(u"tableWidget_shot_exr")
        self.tableWidget_shot_exr.setGeometry(QRect(10, 10, 496, 378))
        self.tableWidget_shot_exr.setFont(font1)
        self.tableWidget_shot_exr.horizontalHeader().setVisible(False)
        self.tableWidget_shot_exr.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_shot_exr.verticalHeader().setVisible(False)
        self.tableWidget_shot_exr.verticalHeader().setDefaultSectionSize(90)
        self.tabWidget_shot_task.addTab(self.tab_exr, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tableWidget_shot_mov = QTableWidget(self.tab_5)
        self.tableWidget_shot_mov.setObjectName(u"tableWidget_shot_mov")
        self.tableWidget_shot_mov.setGeometry(QRect(10, 10, 496, 378))
        self.tableWidget_shot_mov.setFont(font1)
        self.tableWidget_shot_mov.horizontalHeader().setVisible(False)
        self.tableWidget_shot_mov.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget_shot_mov.verticalHeader().setVisible(False)
        self.tableWidget_shot_mov.verticalHeader().setDefaultSectionSize(90)
        self.tabWidget_shot_task.addTab(self.tab_5, "")
        self.tab_all = QWidget()
        self.tab_all.setObjectName(u"tab_all")
        self.listWidget_shot_allfile = QListWidget(self.tab_all)
        self.listWidget_shot_allfile.setObjectName(u"listWidget_shot_allfile")
        self.listWidget_shot_allfile.setGeometry(QRect(10, 47, 496, 341))
        font2 = QFont()
        font2.setPointSize(13)
        font2.setBold(False)
        self.listWidget_shot_allfile.setFont(font2)
        self.listWidget_shot_allfile.setFrameShape(QFrame.HLine)
        self.listWidget_shot_allfile.setMidLineWidth(0)
        self.listWidget_shot_allfile.setDragEnabled(False)
        self.listWidget_shot_allfile.setDefaultDropAction(Qt.MoveAction)
        self.listWidget_shot_allfile.setMovement(QListView.Static)
        self.listWidget_shot_allfile.setProperty("isWrapping", False)
        self.listWidget_shot_allfile.setLayoutMode(QListView.SinglePass)
        self.listWidget_shot_allfile.setViewMode(QListView.ListMode)
        self.listWidget_shot_allfile.setModelColumn(0)
        self.listWidget_shot_allfile.setSortingEnabled(True)
        self.lineEdit_alllist_search = QLineEdit(self.tab_all)
        self.lineEdit_alllist_search.setObjectName(u"lineEdit_alllist_search")
        self.lineEdit_alllist_search.setGeometry(QRect(10, 10, 401, 26))
        font3 = QFont()
        font3.setBold(False)
        self.lineEdit_alllist_search.setFont(font3)
        self.pushButton_search = QPushButton(self.tab_all)
        self.pushButton_search.setObjectName(u"pushButton_search")
        self.pushButton_search.setGeometry(QRect(420, 10, 84, 27))
        self.tabWidget_shot_task.addTab(self.tab_all, "")

        self.gridLayout.addWidget(self.tabWidget_shot_task, 0, 1, 1, 1)

        self.label_shot_filepath = QLabel(self.tab_shot)
        self.label_shot_filepath.setObjectName(u"label_shot_filepath")
        self.label_shot_filepath.setGeometry(QRect(290, 20, 521, 19))
        self.label_shot_filepath.setFont(font1)
        self.groupBox_shot_comment = QGroupBox(self.tab_shot)
        self.groupBox_shot_comment.setObjectName(u"groupBox_shot_comment")
        self.groupBox_shot_comment.setGeometry(QRect(820, 250, 231, 181))
        font4 = QFont()
        font4.setBold(True)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        self.groupBox_shot_comment.setFont(font4)
        self.groupBox_shot_comment.setFlat(False)
        self.groupBox_shot_comment.setCheckable(False)
        self.plainTextEdit_shot_comment = QPlainTextEdit(self.groupBox_shot_comment)
        self.plainTextEdit_shot_comment.setObjectName(u"plainTextEdit_shot_comment")
        self.plainTextEdit_shot_comment.setGeometry(QRect(0, 20, 231, 161))
        self.tabWidget_shot_status = QTabWidget(self.tab_shot)
        self.tabWidget_shot_status.setObjectName(u"tabWidget_shot_status")
        self.tabWidget_shot_status.setGeometry(QRect(10, 490, 1041, 221))
        self.tabWidget_shot_status.setUsesScrollButtons(True)
        self.tabWidget_shot_status.setDocumentMode(True)
        self.tabWidget_shot_status.setTabsClosable(False)
        self.tabWidget_shot_status.setMovable(True)
        self.tabWidget_shot_status.setTabBarAutoHide(False)
        self.tab_shot_mm = QWidget()
        self.tab_shot_mm.setObjectName(u"tab_shot_mm")
        self.tableWidget_shot_mm = QTableWidget(self.tab_shot_mm)
        self.tableWidget_shot_mm.setObjectName(u"tableWidget_shot_mm")
        self.tableWidget_shot_mm.setGeometry(QRect(0, 10, 1041, 181))
        self.tabWidget_shot_status.addTab(self.tab_shot_mm, "")
        self.tab_shot_ldv = QWidget()
        self.tab_shot_ldv.setObjectName(u"tab_shot_ldv")
        self.tableWidget_shot_ldv = QTableWidget(self.tab_shot_ldv)
        self.tableWidget_shot_ldv.setObjectName(u"tableWidget_shot_ldv")
        self.tableWidget_shot_ldv.setGeometry(QRect(0, 10, 1041, 181))
        self.tabWidget_shot_status.addTab(self.tab_shot_ldv, "")
        self.tab_shot_lit = QWidget()
        self.tab_shot_lit.setObjectName(u"tab_shot_lit")
        self.tableWidget_shot_lit = QTableWidget(self.tab_shot_lit)
        self.tableWidget_shot_lit.setObjectName(u"tableWidget_shot_lit")
        self.tableWidget_shot_lit.setGeometry(QRect(0, 10, 1041, 181))
        self.tabWidget_shot_status.addTab(self.tab_shot_lit, "")
        self.tab_shot_fx = QWidget()
        self.tab_shot_fx.setObjectName(u"tab_shot_fx")
        self.tableWidget_shot_fx = QTableWidget(self.tab_shot_fx)
        self.tableWidget_shot_fx.setObjectName(u"tableWidget_shot_fx")
        self.tableWidget_shot_fx.setGeometry(QRect(0, 10, 1041, 181))
        self.tabWidget_shot_status.addTab(self.tab_shot_fx, "")
        self.tab_shot_comp = QWidget()
        self.tab_shot_comp.setObjectName(u"tab_shot_comp")
        self.tableWidget_shot_comp = QTableWidget(self.tab_shot_comp)
        self.tableWidget_shot_comp.setObjectName(u"tableWidget_shot_comp")
        self.tableWidget_shot_comp.setGeometry(QRect(0, 10, 1041, 181))
        self.tabWidget_shot_status.addTab(self.tab_shot_comp, "")
        self.groupBox_shot_file_info = QGroupBox(self.tab_shot)
        self.groupBox_shot_file_info.setObjectName(u"groupBox_shot_file_info")
        self.groupBox_shot_file_info.setGeometry(QRect(820, 50, 231, 191))
        self.groupBox_shot_file_info.setFont(font4)
        self.groupBox_shot_file_info.setFlat(False)
        self.groupBox_shot_file_info.setCheckable(False)
        self.verticalLayoutWidget = QWidget(self.groupBox_shot_file_info)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_16 = QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName(u"label_16")
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(False)
        font5.setUnderline(False)
        font5.setStrikeOut(False)
        self.label_16.setFont(font5)

        self.verticalLayout_3.addWidget(self.label_16)

        self.label_14 = QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font5)

        self.verticalLayout_3.addWidget(self.label_14)

        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font5)

        self.verticalLayout_3.addWidget(self.label_10)

        self.label_6 = QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font5)

        self.verticalLayout_3.addWidget(self.label_6)

        self.label_9 = QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font5)

        self.verticalLayout_3.addWidget(self.label_9)

        self.label_20 = QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setFont(font5)

        self.verticalLayout_3.addWidget(self.label_20)

        self.verticalLayoutWidget_2 = QWidget(self.groupBox_shot_file_info)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_shot_filename = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filename.setObjectName(u"label_shot_filename")
        self.label_shot_filename.setFont(font5)

        self.verticalLayout_4.addWidget(self.label_shot_filename)

        self.label_shot_filetype = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filetype.setObjectName(u"label_shot_filetype")
        self.label_shot_filetype.setFont(font5)

        self.verticalLayout_4.addWidget(self.label_shot_filetype)

        self.label_shot_framerange = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_framerange.setObjectName(u"label_shot_framerange")
        self.label_shot_framerange.setFont(font5)

        self.verticalLayout_4.addWidget(self.label_shot_framerange)

        self.label_shot_resolution = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_resolution.setObjectName(u"label_shot_resolution")
        self.label_shot_resolution.setFont(font5)

        self.verticalLayout_4.addWidget(self.label_shot_resolution)

        self.label_shot_savedtime = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_savedtime.setObjectName(u"label_shot_savedtime")
        self.label_shot_savedtime.setFont(font5)

        self.verticalLayout_4.addWidget(self.label_shot_savedtime)

        self.label_shot_filesize = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filesize.setObjectName(u"label_shot_filesize")
        self.label_shot_filesize.setFont(font5)

        self.verticalLayout_4.addWidget(self.label_shot_filesize)

        self.pushButton_shot_nuke = QPushButton(self.tab_shot)
        self.pushButton_shot_nuke.setObjectName(u"pushButton_shot_nuke")
        self.pushButton_shot_nuke.setGeometry(QRect(820, 440, 231, 41))
        self.treeWidget = QTreeWidget(self.tab_shot)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(10, 20, 271, 461))
        font6 = QFont()
        font6.setPointSize(20)
        font6.setBold(False)
        self.treeWidget.setFont(font6)
        self.tabWidget_all.addTab(self.tab_shot, "")
        self.tab_my_task = QWidget()
        self.tab_my_task.setObjectName(u"tab_my_task")
        self.tableWidget_mytask_status = QTabWidget(self.tab_my_task)
        self.tableWidget_mytask_status.setObjectName(u"tableWidget_mytask_status")
        self.tableWidget_mytask_status.setGeometry(QRect(10, 490, 1041, 221))
        self.tableWidget_mytask_status.setUsesScrollButtons(True)
        self.tableWidget_mytask_status.setDocumentMode(True)
        self.tableWidget_mytask_status.setTabsClosable(False)
        self.tableWidget_mytask_status.setMovable(True)
        self.tableWidget_mytask_status.setTabBarAutoHide(False)
        self.tab_mt_mm = QWidget()
        self.tab_mt_mm.setObjectName(u"tab_mt_mm")
        self.tableWidget_mytask_mm = QTableWidget(self.tab_mt_mm)
        self.tableWidget_mytask_mm.setObjectName(u"tableWidget_mytask_mm")
        self.tableWidget_mytask_mm.setGeometry(QRect(0, 10, 1041, 181))
        self.tableWidget_mytask_status.addTab(self.tab_mt_mm, "")
        self.tab_mt_ldv = QWidget()
        self.tab_mt_ldv.setObjectName(u"tab_mt_ldv")
        self.tableWidget_mytask_ldv = QTableWidget(self.tab_mt_ldv)
        self.tableWidget_mytask_ldv.setObjectName(u"tableWidget_mytask_ldv")
        self.tableWidget_mytask_ldv.setGeometry(QRect(0, 10, 1041, 181))
        self.tableWidget_mytask_status.addTab(self.tab_mt_ldv, "")
        self.tab_mt_lit = QWidget()
        self.tab_mt_lit.setObjectName(u"tab_mt_lit")
        self.tableWidget_mytask_lit = QTableWidget(self.tab_mt_lit)
        self.tableWidget_mytask_lit.setObjectName(u"tableWidget_mytask_lit")
        self.tableWidget_mytask_lit.setGeometry(QRect(0, 10, 1041, 181))
        self.tableWidget_mytask_status.addTab(self.tab_mt_lit, "")
        self.tab_mt_fx = QWidget()
        self.tab_mt_fx.setObjectName(u"tab_mt_fx")
        self.tableWidget_mytask_fx = QTableWidget(self.tab_mt_fx)
        self.tableWidget_mytask_fx.setObjectName(u"tableWidget_mytask_fx")
        self.tableWidget_mytask_fx.setGeometry(QRect(0, 10, 1041, 181))
        self.tableWidget_mytask_status.addTab(self.tab_mt_fx, "")
        self.tab_mt_comp = QWidget()
        self.tab_mt_comp.setObjectName(u"tab_mt_comp")
        self.tableWidget_mytask_comp = QTableWidget(self.tab_mt_comp)
        self.tableWidget_mytask_comp.setObjectName(u"tableWidget_mytask_comp")
        self.tableWidget_mytask_comp.setGeometry(QRect(0, 10, 1041, 181))
        self.tableWidget_mytask_status.addTab(self.tab_mt_comp, "")
        self.groupBox_shot_comment_2 = QGroupBox(self.tab_my_task)
        self.groupBox_shot_comment_2.setObjectName(u"groupBox_shot_comment_2")
        self.groupBox_shot_comment_2.setGeometry(QRect(820, 50, 231, 331))
        self.groupBox_shot_comment_2.setFont(font4)
        self.groupBox_shot_comment_2.setFlat(False)
        self.groupBox_shot_comment_2.setCheckable(False)
        self.plainTextEdit_mytask_comment = QPlainTextEdit(self.groupBox_shot_comment_2)
        self.plainTextEdit_mytask_comment.setObjectName(u"plainTextEdit_mytask_comment")
        self.plainTextEdit_mytask_comment.setGeometry(QRect(0, 20, 231, 311))
        self.pushButton_mytask_selectedopen = QPushButton(self.tab_my_task)
        self.pushButton_mytask_selectedopen.setObjectName(u"pushButton_mytask_selectedopen")
        self.pushButton_mytask_selectedopen.setGeometry(QRect(820, 440, 231, 41))
        self.label_mytask_filepath = QLabel(self.tab_my_task)
        self.label_mytask_filepath.setObjectName(u"label_mytask_filepath")
        self.label_mytask_filepath.setGeometry(QRect(10, 8, 521, 41))
        font7 = QFont()
        font7.setPointSize(18)
        font7.setBold(True)
        self.label_mytask_filepath.setFont(font7)
        self.pushButton_mytask_newfileopen = QPushButton(self.tab_my_task)
        self.pushButton_mytask_newfileopen.setObjectName(u"pushButton_mytask_newfileopen")
        self.pushButton_mytask_newfileopen.setGeometry(QRect(820, 390, 231, 41))
        self.tableWidget_recent_files = QTableWidget(self.tab_my_task)
        self.tableWidget_recent_files.setObjectName(u"tableWidget_recent_files")
        self.tableWidget_recent_files.setGeometry(QRect(10, 50, 500, 431))
        self.tableWidget_recent_files.horizontalHeader().setVisible(True)
        self.tableWidget_recent_files.verticalHeader().setVisible(False)
        self.groupBox_shot_comment_3 = QGroupBox(self.tab_my_task)
        self.groupBox_shot_comment_3.setObjectName(u"groupBox_shot_comment_3")
        self.groupBox_shot_comment_3.setGeometry(QRect(530, 50, 271, 220))
        self.groupBox_shot_comment_3.setFont(font4)
        self.groupBox_shot_comment_3.setFlat(False)
        self.groupBox_shot_comment_3.setCheckable(False)
        self.label_shot_comment_2 = QLabel(self.groupBox_shot_comment_3)
        self.label_shot_comment_2.setObjectName(u"label_shot_comment_2")
        self.label_shot_comment_2.setGeometry(QRect(10, 30, 211, 141))
        self.label_mytask_thumbnail = QLabel(self.groupBox_shot_comment_3)
        self.label_mytask_thumbnail.setObjectName(u"label_mytask_thumbnail")
        self.label_mytask_thumbnail.setGeometry(QRect(-1, 19, 271, 201))
        self.groupBox_shot_file_info_2 = QGroupBox(self.tab_my_task)
        self.groupBox_shot_file_info_2.setObjectName(u"groupBox_shot_file_info_2")
        self.groupBox_shot_file_info_2.setGeometry(QRect(530, 290, 271, 191))
        self.groupBox_shot_file_info_2.setFont(font4)
        self.groupBox_shot_file_info_2.setFlat(False)
        self.groupBox_shot_file_info_2.setCheckable(False)
        self.verticalLayoutWidget_3 = QWidget(self.groupBox_shot_file_info_2)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_5 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.verticalLayoutWidget_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setFont(font5)

        self.verticalLayout_5.addWidget(self.label_17)

        self.label_15 = QLabel(self.verticalLayoutWidget_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setFont(font5)

        self.verticalLayout_5.addWidget(self.label_15)

        self.label_12 = QLabel(self.verticalLayoutWidget_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setFont(font5)

        self.verticalLayout_5.addWidget(self.label_12)

        self.label_13 = QLabel(self.verticalLayoutWidget_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font5)

        self.verticalLayout_5.addWidget(self.label_13)

        self.label_21 = QLabel(self.verticalLayoutWidget_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setFont(font5)

        self.verticalLayout_5.addWidget(self.label_21)

        self.verticalLayoutWidget_4 = QWidget(self.groupBox_shot_file_info_2)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(90, 30, 171, 151))
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_mytask_filename = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_filename.setObjectName(u"label_mytask_filename")
        self.label_mytask_filename.setFont(font5)

        self.verticalLayout_6.addWidget(self.label_mytask_filename)

        self.label_mytask_filetype = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_filetype.setObjectName(u"label_mytask_filetype")
        self.label_mytask_filetype.setFont(font5)

        self.verticalLayout_6.addWidget(self.label_mytask_filetype)

        self.label_mytask_resolution = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_resolution.setObjectName(u"label_mytask_resolution")
        self.label_mytask_resolution.setFont(font5)

        self.verticalLayout_6.addWidget(self.label_mytask_resolution)

        self.label_mytask_savedtime = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_savedtime.setObjectName(u"label_mytask_savedtime")
        self.label_mytask_savedtime.setFont(font5)

        self.verticalLayout_6.addWidget(self.label_mytask_savedtime)

        self.label_mytask_filesize = QLabel(self.verticalLayoutWidget_4)
        self.label_mytask_filesize.setObjectName(u"label_mytask_filesize")
        self.label_mytask_filesize.setFont(font5)

        self.verticalLayout_6.addWidget(self.label_mytask_filesize)

        self.tabWidget_all.addTab(self.tab_my_task, "")
        self.tab_clip = QWidget()
        self.tab_clip.setObjectName(u"tab_clip")
        self.gridLayoutWidget_2 = QWidget(self.tab_clip)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(10, 20, 1051, 691))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_template = QTabWidget(self.gridLayoutWidget_2)
        self.tabWidget_template.setObjectName(u"tabWidget_template")
        self.tabWidget_template.setFont(font)
        self.tab_asset = QWidget()
        self.tab_asset.setObjectName(u"tab_asset")
        self.pushButton_asset_nuke = QPushButton(self.tab_asset)
        self.pushButton_asset_nuke.setObjectName(u"pushButton_asset_nuke")
        self.pushButton_asset_nuke.setGeometry(QRect(810, 610, 231, 41))
        self.groupBox_asset_comment = QGroupBox(self.tab_asset)
        self.groupBox_asset_comment.setObjectName(u"groupBox_asset_comment")
        self.groupBox_asset_comment.setGeometry(QRect(810, 420, 231, 181))
        self.groupBox_asset_comment.setFont(font4)
        self.groupBox_asset_comment.setFlat(False)
        self.groupBox_asset_comment.setCheckable(False)
        self.label_asset_comment = QLabel(self.groupBox_asset_comment)
        self.label_asset_comment.setObjectName(u"label_asset_comment")
        self.label_asset_comment.setGeometry(QRect(10, 30, 211, 141))
        self.groupBox_asset_file_info = QGroupBox(self.tab_asset)
        self.groupBox_asset_file_info.setObjectName(u"groupBox_asset_file_info")
        self.groupBox_asset_file_info.setGeometry(QRect(810, 10, 231, 401))
        self.groupBox_asset_file_info.setFont(font4)
        self.groupBox_asset_file_info.setFlat(False)
        self.groupBox_asset_file_info.setCheckable(False)
        self.verticalLayoutWidget_5 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_23 = QLabel(self.verticalLayoutWidget_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setFont(font5)

        self.verticalLayout_7.addWidget(self.label_23)

        self.label_24 = QLabel(self.verticalLayoutWidget_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setFont(font5)

        self.verticalLayout_7.addWidget(self.label_24)

        self.label_25 = QLabel(self.verticalLayoutWidget_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setFont(font5)

        self.verticalLayout_7.addWidget(self.label_25)

        self.label_26 = QLabel(self.verticalLayoutWidget_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setFont(font5)

        self.verticalLayout_7.addWidget(self.label_26)

        self.label_27 = QLabel(self.verticalLayoutWidget_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setFont(font5)

        self.verticalLayout_7.addWidget(self.label_27)

        self.label_28 = QLabel(self.verticalLayoutWidget_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setFont(font5)

        self.verticalLayout_7.addWidget(self.label_28)

        self.verticalLayoutWidget_6 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_8 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_asset_filename = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filename.setObjectName(u"label_asset_filename")
        self.label_asset_filename.setFont(font5)

        self.verticalLayout_8.addWidget(self.label_asset_filename)

        self.label_asset_filetype = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filetype.setObjectName(u"label_asset_filetype")
        self.label_asset_filetype.setFont(font5)

        self.verticalLayout_8.addWidget(self.label_asset_filetype)

        self.label_asset_framerange = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_framerange.setObjectName(u"label_asset_framerange")
        self.label_asset_framerange.setFont(font5)

        self.verticalLayout_8.addWidget(self.label_asset_framerange)

        self.label_asset_resolution = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_resolution.setObjectName(u"label_asset_resolution")
        self.label_asset_resolution.setFont(font5)

        self.verticalLayout_8.addWidget(self.label_asset_resolution)

        self.label_asset_savedtime = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_savedtime.setObjectName(u"label_asset_savedtime")
        self.label_asset_savedtime.setFont(font5)

        self.verticalLayout_8.addWidget(self.label_asset_savedtime)

        self.label_asset_filesize = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filesize.setObjectName(u"label_asset_filesize")
        self.label_asset_filesize.setFont(font5)

        self.verticalLayout_8.addWidget(self.label_asset_filesize)

        self.line = QFrame(self.groupBox_asset_file_info)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 175, 231, 31))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.verticalLayoutWidget_11 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_11.setObjectName(u"verticalLayoutWidget_11")
        self.verticalLayoutWidget_11.setGeometry(QRect(10, 200, 71, 42))
        self.verticalLayout_13 = QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.label_47 = QLabel(self.verticalLayoutWidget_11)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setFont(font5)

        self.verticalLayout_13.addWidget(self.label_47)

        self.label_48 = QLabel(self.verticalLayoutWidget_11)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setFont(font5)

        self.verticalLayout_13.addWidget(self.label_48)

        self.verticalLayoutWidget_12 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_12.setObjectName(u"verticalLayoutWidget_12")
        self.verticalLayoutWidget_12.setGeometry(QRect(90, 200, 131, 42))
        self.verticalLayout_14 = QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.label_asset_version = QLabel(self.verticalLayoutWidget_12)
        self.label_asset_version.setObjectName(u"label_asset_version")
        self.label_asset_version.setFont(font5)

        self.verticalLayout_14.addWidget(self.label_asset_version)

        self.label_asset_pubdate = QLabel(self.verticalLayoutWidget_12)
        self.label_asset_pubdate.setObjectName(u"label_asset_pubdate")
        self.label_asset_pubdate.setFont(font5)

        self.verticalLayout_14.addWidget(self.label_asset_pubdate)

        self.toolBox_asset_task = QToolBox(self.tab_asset)
        self.toolBox_asset_task.setObjectName(u"toolBox_asset_task")
        self.toolBox_asset_task.setGeometry(QRect(10, 57, 791, 591))
        self.toolBox_asset_task.setFont(font)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.page_5.setGeometry(QRect(0, 0, 791, 525))
        self.tableWidget_asset_mdl_asset = QTableWidget(self.page_5)
        self.tableWidget_asset_mdl_asset.setObjectName(u"tableWidget_asset_mdl_asset")
        self.tableWidget_asset_mdl_asset.setGeometry(QRect(240, 0, 551, 525))
        self.listWidget_cache_name = QListWidget(self.page_5)
        self.listWidget_cache_name.setObjectName(u"listWidget_cache_name")
        self.listWidget_cache_name.setGeometry(QRect(0, 0, 231, 525))
        self.toolBox_asset_task.addItem(self.page_5, u"MDL")
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setGeometry(QRect(0, 0, 100, 30))
        self.tableWidget_asset_ani_asset = QTableWidget(self.page_6)
        self.tableWidget_asset_ani_asset.setObjectName(u"tableWidget_asset_ani_asset")
        self.tableWidget_asset_ani_asset.setGeometry(QRect(0, 1, 501, 564))
        self.toolBox_asset_task.addItem(self.page_6, u"ANI")
        self.horizontalLayoutWidget_3 = QWidget(self.tab_asset)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 0, 291, 61))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.horizontalLayoutWidget_3)
        self.label_4.setObjectName(u"label_4")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy1)
        self.label_4.setFont(font3)

        self.horizontalLayout_3.addWidget(self.label_4)

        self.comboBox_asset_type = QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox_asset_type.setObjectName(u"comboBox_asset_type")

        self.horizontalLayout_3.addWidget(self.comboBox_asset_type)

        self.tabWidget_template.addTab(self.tab_asset, "")
        self.tab_clip1 = QWidget()
        self.tab_clip1.setObjectName(u"tab_clip1")
        self.groupBox_asset_file_info_2 = QGroupBox(self.tab_clip1)
        self.groupBox_asset_file_info_2.setObjectName(u"groupBox_asset_file_info_2")
        self.groupBox_asset_file_info_2.setGeometry(QRect(800, 10, 231, 641))
        self.groupBox_asset_file_info_2.setFont(font4)
        self.groupBox_asset_file_info_2.setFlat(False)
        self.groupBox_asset_file_info_2.setCheckable(False)
        self.verticalLayoutWidget_13 = QWidget(self.groupBox_asset_file_info_2)
        self.verticalLayoutWidget_13.setObjectName(u"verticalLayoutWidget_13")
        self.verticalLayoutWidget_13.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_15 = QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.label_51 = QLabel(self.verticalLayoutWidget_13)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setFont(font5)

        self.verticalLayout_15.addWidget(self.label_51)

        self.label_52 = QLabel(self.verticalLayoutWidget_13)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setFont(font5)

        self.verticalLayout_15.addWidget(self.label_52)

        self.label_53 = QLabel(self.verticalLayoutWidget_13)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setFont(font5)

        self.verticalLayout_15.addWidget(self.label_53)

        self.label_54 = QLabel(self.verticalLayoutWidget_13)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setFont(font5)

        self.verticalLayout_15.addWidget(self.label_54)

        self.label_55 = QLabel(self.verticalLayoutWidget_13)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setFont(font5)

        self.verticalLayout_15.addWidget(self.label_55)

        self.label_56 = QLabel(self.verticalLayoutWidget_13)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setFont(font5)

        self.verticalLayout_15.addWidget(self.label_56)

        self.verticalLayoutWidget_14 = QWidget(self.groupBox_asset_file_info_2)
        self.verticalLayoutWidget_14.setObjectName(u"verticalLayoutWidget_14")
        self.verticalLayoutWidget_14.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_16 = QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.label_clip_filename = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filename.setObjectName(u"label_clip_filename")
        self.label_clip_filename.setFont(font5)

        self.verticalLayout_16.addWidget(self.label_clip_filename)

        self.label_clip_filetype = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filetype.setObjectName(u"label_clip_filetype")
        self.label_clip_filetype.setFont(font5)

        self.verticalLayout_16.addWidget(self.label_clip_filetype)

        self.label_clip_framerange = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_framerange.setObjectName(u"label_clip_framerange")
        self.label_clip_framerange.setFont(font5)

        self.verticalLayout_16.addWidget(self.label_clip_framerange)

        self.label_clip_resolution = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_resolution.setObjectName(u"label_clip_resolution")
        self.label_clip_resolution.setFont(font5)

        self.verticalLayout_16.addWidget(self.label_clip_resolution)

        self.label_clip_savedtime = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_savedtime.setObjectName(u"label_clip_savedtime")
        self.label_clip_savedtime.setFont(font5)

        self.verticalLayout_16.addWidget(self.label_clip_savedtime)

        self.label_clip_filesize = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filesize.setObjectName(u"label_clip_filesize")
        self.label_clip_filesize.setFont(font5)

        self.verticalLayout_16.addWidget(self.label_clip_filesize)

        self.tableWidget_clip_files = QTableWidget(self.tab_clip1)
        self.tableWidget_clip_files.setObjectName(u"tableWidget_clip_files")
        self.tableWidget_clip_files.setGeometry(QRect(10, 10, 781, 641))
        font8 = QFont()
        font8.setPointSize(10)
        font8.setBold(False)
        self.tableWidget_clip_files.setFont(font8)
        self.tableWidget_clip_files.horizontalHeader().setVisible(False)
        self.tableWidget_clip_files.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget_clip_files.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_clip_files.verticalHeader().setVisible(False)
        self.tableWidget_clip_files.verticalHeader().setMinimumSectionSize(50)
        self.tableWidget_clip_files.verticalHeader().setDefaultSectionSize(100)
        self.tabWidget_template.addTab(self.tab_clip1, "")
        self.tab_nodes = QWidget()
        self.tab_nodes.setObjectName(u"tab_nodes")
        self.groupBox_nodes_file_info = QGroupBox(self.tab_nodes)
        self.groupBox_nodes_file_info.setObjectName(u"groupBox_nodes_file_info")
        self.groupBox_nodes_file_info.setGeometry(QRect(800, 10, 231, 401))
        self.groupBox_nodes_file_info.setFont(font4)
        self.groupBox_nodes_file_info.setFlat(False)
        self.groupBox_nodes_file_info.setCheckable(False)
        self.verticalLayoutWidget_21 = QWidget(self.groupBox_nodes_file_info)
        self.verticalLayoutWidget_21.setObjectName(u"verticalLayoutWidget_21")
        self.verticalLayoutWidget_21.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_23 = QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.label_59 = QLabel(self.verticalLayoutWidget_21)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setFont(font5)

        self.verticalLayout_23.addWidget(self.label_59)

        self.label_60 = QLabel(self.verticalLayoutWidget_21)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setFont(font5)

        self.verticalLayout_23.addWidget(self.label_60)

        self.label_75 = QLabel(self.verticalLayoutWidget_21)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setFont(font5)

        self.verticalLayout_23.addWidget(self.label_75)

        self.label_76 = QLabel(self.verticalLayoutWidget_21)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setFont(font5)

        self.verticalLayout_23.addWidget(self.label_76)

        self.label_77 = QLabel(self.verticalLayoutWidget_21)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setFont(font5)

        self.verticalLayout_23.addWidget(self.label_77)

        self.label_78 = QLabel(self.verticalLayoutWidget_21)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setFont(font5)

        self.verticalLayout_23.addWidget(self.label_78)

        self.verticalLayoutWidget_22 = QWidget(self.groupBox_nodes_file_info)
        self.verticalLayoutWidget_22.setObjectName(u"verticalLayoutWidget_22")
        self.verticalLayoutWidget_22.setGeometry(QRect(90, 30, 131, 151))
        self.verticalLayout_24 = QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.label_nodes_filename = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_filename.setObjectName(u"label_nodes_filename")
        self.label_nodes_filename.setFont(font5)

        self.verticalLayout_24.addWidget(self.label_nodes_filename)

        self.label_nodes_filetype = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_filetype.setObjectName(u"label_nodes_filetype")
        self.label_nodes_filetype.setFont(font5)

        self.verticalLayout_24.addWidget(self.label_nodes_filetype)

        self.label_nodes_framerange = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_framerange.setObjectName(u"label_nodes_framerange")
        self.label_nodes_framerange.setFont(font5)

        self.verticalLayout_24.addWidget(self.label_nodes_framerange)

        self.label_nodes_resolution = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_resolution.setObjectName(u"label_nodes_resolution")
        self.label_nodes_resolution.setFont(font5)

        self.verticalLayout_24.addWidget(self.label_nodes_resolution)

        self.label_nodes_savedtime = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_savedtime.setObjectName(u"label_nodes_savedtime")
        self.label_nodes_savedtime.setFont(font5)

        self.verticalLayout_24.addWidget(self.label_nodes_savedtime)

        self.label_nodes_filesize = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_filesize.setObjectName(u"label_nodes_filesize")
        self.label_nodes_filesize.setFont(font5)

        self.verticalLayout_24.addWidget(self.label_nodes_filesize)

        self.line_4 = QFrame(self.groupBox_nodes_file_info)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 175, 231, 31))
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.listWidget_nodes_info = QListWidget(self.groupBox_nodes_file_info)
        self.listWidget_nodes_info.setObjectName(u"listWidget_nodes_info")
        self.listWidget_nodes_info.setGeometry(QRect(10, 221, 211, 171))
        self.label_49 = QLabel(self.groupBox_nodes_file_info)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 200, 63, 19))
        self.pushButton_clip_nuke_2 = QPushButton(self.tab_nodes)
        self.pushButton_clip_nuke_2.setObjectName(u"pushButton_clip_nuke_2")
        self.pushButton_clip_nuke_2.setGeometry(QRect(800, 610, 231, 41))
        self.groupBox_clip_comment_3 = QGroupBox(self.tab_nodes)
        self.groupBox_clip_comment_3.setObjectName(u"groupBox_clip_comment_3")
        self.groupBox_clip_comment_3.setGeometry(QRect(800, 420, 231, 181))
        self.groupBox_clip_comment_3.setFont(font4)
        self.groupBox_clip_comment_3.setFlat(False)
        self.groupBox_clip_comment_3.setCheckable(False)
        self.label_82 = QLabel(self.groupBox_clip_comment_3)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(10, 30, 211, 141))
        font9 = QFont()
        font9.setBold(False)
        font9.setUnderline(False)
        font9.setStrikeOut(False)
        self.label_82.setFont(font9)
        self.tableWidget_nodes_files = QTableWidget(self.tab_nodes)
        self.tableWidget_nodes_files.setObjectName(u"tableWidget_nodes_files")
        self.tableWidget_nodes_files.setGeometry(QRect(240, 10, 551, 641))
        self.tabWidget_template.addTab(self.tab_nodes, "")

        self.gridLayout_3.addWidget(self.tabWidget_template, 0, 0, 1, 1)

        self.tabWidget_all.addTab(self.tab_clip, "")
        self.tab_pub = QWidget()
        self.tab_pub.setObjectName(u"tab_pub")
        self.groupBox_shot_file_info_3 = QGroupBox(self.tab_pub)
        self.groupBox_shot_file_info_3.setObjectName(u"groupBox_shot_file_info_3")
        self.groupBox_shot_file_info_3.setGeometry(QRect(780, 470, 271, 191))
        self.groupBox_shot_file_info_3.setFont(font4)
        self.groupBox_shot_file_info_3.setFlat(False)
        self.groupBox_shot_file_info_3.setCheckable(False)
        self.verticalLayoutWidget_9 = QWidget(self.groupBox_shot_file_info_3)
        self.verticalLayoutWidget_9.setObjectName(u"verticalLayoutWidget_9")
        self.verticalLayoutWidget_9.setGeometry(QRect(10, 30, 74, 151))
        self.verticalLayout_11 = QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_34 = QLabel(self.verticalLayoutWidget_9)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_34)

        self.label_35 = QLabel(self.verticalLayoutWidget_9)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_35)

        self.label_36 = QLabel(self.verticalLayoutWidget_9)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_36)

        self.label_37 = QLabel(self.verticalLayoutWidget_9)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_37)

        self.label_38 = QLabel(self.verticalLayoutWidget_9)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_38)

        self.label_39 = QLabel(self.verticalLayoutWidget_9)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setFont(font5)

        self.verticalLayout_11.addWidget(self.label_39)

        self.verticalLayoutWidget_10 = QWidget(self.groupBox_shot_file_info_3)
        self.verticalLayoutWidget_10.setObjectName(u"verticalLayoutWidget_10")
        self.verticalLayoutWidget_10.setGeometry(QRect(90, 30, 171, 151))
        self.verticalLayout_12 = QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.label_pub_filename = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_filename.setObjectName(u"label_pub_filename")
        self.label_pub_filename.setFont(font5)

        self.verticalLayout_12.addWidget(self.label_pub_filename)

        self.label_pub_filetype = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_filetype.setObjectName(u"label_pub_filetype")
        self.label_pub_filetype.setFont(font5)

        self.verticalLayout_12.addWidget(self.label_pub_filetype)

        self.label_pub_framerange = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_framerange.setObjectName(u"label_pub_framerange")
        self.label_pub_framerange.setFont(font5)

        self.verticalLayout_12.addWidget(self.label_pub_framerange)

        self.label_pub_resolution = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_resolution.setObjectName(u"label_pub_resolution")
        self.label_pub_resolution.setFont(font5)

        self.verticalLayout_12.addWidget(self.label_pub_resolution)

        self.label_pub_savedtime = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_savedtime.setObjectName(u"label_pub_savedtime")
        self.label_pub_savedtime.setFont(font5)

        self.verticalLayout_12.addWidget(self.label_pub_savedtime)

        self.label_pub_filesize = QLabel(self.verticalLayoutWidget_10)
        self.label_pub_filesize.setObjectName(u"label_pub_filesize")
        self.label_pub_filesize.setFont(font5)

        self.verticalLayout_12.addWidget(self.label_pub_filesize)

        self.pushButton_pub_publish = QPushButton(self.tab_pub)
        self.pushButton_pub_publish.setObjectName(u"pushButton_pub_publish")
        self.pushButton_pub_publish.setGeometry(QRect(920, 670, 131, 41))
        self.groupBox_shot_comment_4 = QGroupBox(self.tab_pub)
        self.groupBox_shot_comment_4.setObjectName(u"groupBox_shot_comment_4")
        self.groupBox_shot_comment_4.setGeometry(QRect(420, 470, 341, 241))
        self.groupBox_shot_comment_4.setFont(font4)
        self.groupBox_shot_comment_4.setFlat(False)
        self.groupBox_shot_comment_4.setCheckable(False)
        self.plainTextEdit_pub_comment = QPlainTextEdit(self.groupBox_shot_comment_4)
        self.plainTextEdit_pub_comment.setObjectName(u"plainTextEdit_pub_comment")
        self.plainTextEdit_pub_comment.setGeometry(QRect(0, 20, 341, 221))
        self.groupBox_shot_comment_5 = QGroupBox(self.tab_pub)
        self.groupBox_shot_comment_5.setObjectName(u"groupBox_shot_comment_5")
        self.groupBox_shot_comment_5.setGeometry(QRect(420, 50, 631, 411))
        self.groupBox_shot_comment_5.setFont(font4)
        self.groupBox_shot_comment_5.setFlat(False)
        self.groupBox_shot_comment_5.setCheckable(False)
        self.label_shot_comment_4 = QLabel(self.groupBox_shot_comment_5)
        self.label_shot_comment_4.setObjectName(u"label_shot_comment_4")
        self.label_shot_comment_4.setGeometry(QRect(10, 30, 211, 141))
        self.label_pub_thumbnail = QLabel(self.groupBox_shot_comment_5)
        self.label_pub_thumbnail.setObjectName(u"label_pub_thumbnail")
        self.label_pub_thumbnail.setGeometry(QRect(0, 20, 631, 391))
        self.label_mytask_filepath_2 = QLabel(self.tab_pub)
        self.label_mytask_filepath_2.setObjectName(u"label_mytask_filepath_2")
        self.label_mytask_filepath_2.setGeometry(QRect(10, 8, 521, 41))
        self.label_mytask_filepath_2.setFont(font7)
        self.treeWidget_pub_list = QTreeWidget(self.tab_pub)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidget_pub_list.setHeaderItem(__qtreewidgetitem1)
        self.treeWidget_pub_list.setObjectName(u"treeWidget_pub_list")
        self.treeWidget_pub_list.setGeometry(QRect(10, 70, 391, 641))
        self.treeWidget_pub_list.header().setVisible(False)
        self.pushButton_pub_retake = QPushButton(self.tab_pub)
        self.pushButton_pub_retake.setObjectName(u"pushButton_pub_retake")
        self.pushButton_pub_retake.setGeometry(QRect(780, 670, 131, 41))
        self.tabWidget_all.addTab(self.tab_pub, "")
        self.horizontalLayoutWidget_2 = QWidget(Form)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(50, 30, 191, 51))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(u"label_3")
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.label_3.setFont(font3)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.comboBox_seq = QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_seq.setObjectName(u"comboBox_seq")

        self.horizontalLayout_2.addWidget(self.comboBox_seq)

        self.gridLayoutWidget_3 = QWidget(Form)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(900, 30, 211, 81))
        self.gridLayout_4 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.gridLayoutWidget_3)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_username = QLabel(self.frame)
        self.label_username.setObjectName(u"label_username")
        self.label_username.setGeometry(QRect(5, 1, 151, 20))
        font10 = QFont()
        font10.setPointSize(8)
        self.label_username.setFont(font10)

        self.gridLayout_4.addWidget(self.frame, 0, 3, 1, 1)

        self.frame_3 = QFrame(self.gridLayoutWidget_3)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.label_rank = QLabel(self.frame_3)
        self.label_rank.setObjectName(u"label_rank")
        self.label_rank.setGeometry(QRect(5, 1, 151, 20))
        self.label_rank.setFont(font10)

        self.gridLayout_4.addWidget(self.frame_3, 1, 3, 1, 1)

        self.frame_2 = QFrame(self.gridLayoutWidget_3)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_projectname = QLabel(self.frame_2)
        self.label_projectname.setObjectName(u"label_projectname")
        self.label_projectname.setGeometry(QRect(5, 0, 151, 21))
        self.label_projectname.setFont(font10)

        self.gridLayout_4.addWidget(self.frame_2, 2, 3, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(u"label_8")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy2)
        font11 = QFont()
        font11.setPointSize(8)
        font11.setBold(True)
        self.label_8.setFont(font11)

        self.gridLayout_4.addWidget(self.label_8, 2, 1, 1, 1)

        self.label_7 = QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(u"label_7")
        sizePolicy2.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy2)
        self.label_7.setFont(font11)

        self.gridLayout_4.addWidget(self.label_7, 0, 1, 1, 1)

        self.label_19 = QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName(u"label_19")
        sizePolicy2.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy2)
        self.label_19.setFont(font11)

        self.gridLayout_4.addWidget(self.label_19, 1, 1, 1, 1)


        self.retranslateUi(Form)

        self.tabWidget_all.setCurrentIndex(0)
        self.tabWidget_shot_task.setCurrentIndex(1)
        self.tabWidget_shot_status.setCurrentIndex(0)
        self.tableWidget_mytask_status.setCurrentIndex(4)
        self.tabWidget_template.setCurrentIndex(0)
        self.toolBox_asset_task.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_work), QCoreApplication.translate("Form", u"WORK", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_exr), QCoreApplication.translate("Form", u"EXR", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_5), QCoreApplication.translate("Form", u"MOV", None))
        self.pushButton_search.setText(QCoreApplication.translate("Form", u"search", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_all), QCoreApplication.translate("Form", u"ALL", None))
        self.label_shot_filepath.setText("")
        self.groupBox_shot_comment.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_mm), QCoreApplication.translate("Form", u"MM", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_ldv), QCoreApplication.translate("Form", u"LDV", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_lit), QCoreApplication.translate("Form", u"LIT", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_fx), QCoreApplication.translate("Form", u"FX", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_comp), QCoreApplication.translate("Form", u"COMP", None))
        self.groupBox_shot_file_info.setTitle(QCoreApplication.translate("Form", u"File information", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_shot_filename.setText("")
        self.label_shot_filetype.setText("")
        self.label_shot_framerange.setText("")
        self.label_shot_resolution.setText("")
        self.label_shot_savedtime.setText("")
        self.label_shot_filesize.setText("")
        self.pushButton_shot_nuke.setText(QCoreApplication.translate("Form", u"NUKE", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_shot), QCoreApplication.translate("Form", u"SHOT", None))
        self.tableWidget_mytask_status.setTabText(self.tableWidget_mytask_status.indexOf(self.tab_mt_mm), QCoreApplication.translate("Form", u"MM", None))
        self.tableWidget_mytask_status.setTabText(self.tableWidget_mytask_status.indexOf(self.tab_mt_ldv), QCoreApplication.translate("Form", u"LDV", None))
        self.tableWidget_mytask_status.setTabText(self.tableWidget_mytask_status.indexOf(self.tab_mt_lit), QCoreApplication.translate("Form", u"LIT", None))
        self.tableWidget_mytask_status.setTabText(self.tableWidget_mytask_status.indexOf(self.tab_mt_fx), QCoreApplication.translate("Form", u"FX", None))
        self.tableWidget_mytask_status.setTabText(self.tableWidget_mytask_status.indexOf(self.tab_mt_comp), QCoreApplication.translate("Form", u"COMP", None))
        self.groupBox_shot_comment_2.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.plainTextEdit_mytask_comment.setPlainText("")
        self.pushButton_mytask_selectedopen.setText(QCoreApplication.translate("Form", u"OPEN", None))
        self.label_mytask_filepath.setText(QCoreApplication.translate("Form", u"RECENT", None))
        self.pushButton_mytask_newfileopen.setText(QCoreApplication.translate("Form", u"NEW", None))
        self.groupBox_shot_comment_3.setTitle(QCoreApplication.translate("Form", u"Thumbnail", None))
        self.label_shot_comment_2.setText("")
        self.label_mytask_thumbnail.setText("")
        self.groupBox_shot_file_info_2.setTitle(QCoreApplication.translate("Form", u"File information", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_mytask_filename.setText("")
        self.label_mytask_filetype.setText("")
        self.label_mytask_resolution.setText("")
        self.label_mytask_savedtime.setText("")
        self.label_mytask_filesize.setText("")
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_my_task), QCoreApplication.translate("Form", u"MY TASK", None))
        self.pushButton_asset_nuke.setText(QCoreApplication.translate("Form", u"IMPORT", None))
        self.groupBox_asset_comment.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_asset_comment.setText("")
        self.groupBox_asset_file_info.setTitle(QCoreApplication.translate("Form", u"Asset information", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_asset_filename.setText("")
        self.label_asset_filetype.setText("")
        self.label_asset_framerange.setText("")
        self.label_asset_resolution.setText("")
        self.label_asset_savedtime.setText("")
        self.label_asset_filesize.setText("")
        self.label_47.setText(QCoreApplication.translate("Form", u"Version", None))
        self.label_48.setText(QCoreApplication.translate("Form", u"Pub date", None))
        self.label_asset_version.setText("")
        self.label_asset_pubdate.setText("")
        self.toolBox_asset_task.setItemText(self.toolBox_asset_task.indexOf(self.page_5), QCoreApplication.translate("Form", u"MDL", None))
        self.toolBox_asset_task.setItemText(self.toolBox_asset_task.indexOf(self.page_6), QCoreApplication.translate("Form", u"ANI", None))
        self.label_4.setText(QCoreApplication.translate("Form", u" Asset type", None))
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_asset), QCoreApplication.translate("Form", u"ASSET (cache)", None))
        self.groupBox_asset_file_info_2.setTitle(QCoreApplication.translate("Form", u"Clip information", None))
        self.label_51.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_52.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_53.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_54.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_55.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_56.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_clip_filename.setText("")
        self.label_clip_filetype.setText("")
        self.label_clip_framerange.setText("")
        self.label_clip_resolution.setText("")
        self.label_clip_savedtime.setText("")
        self.label_clip_filesize.setText("")
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_clip1), QCoreApplication.translate("Form", u"CLIP", None))
        self.groupBox_nodes_file_info.setTitle(QCoreApplication.translate("Form", u"File information", None))
        self.label_59.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_60.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_75.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_76.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_77.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_78.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_nodes_filename.setText("")
        self.label_nodes_filetype.setText("")
        self.label_nodes_framerange.setText("")
        self.label_nodes_resolution.setText("")
        self.label_nodes_savedtime.setText("")
        self.label_nodes_filesize.setText("")
        self.label_49.setText(QCoreApplication.translate("Form", u"Nodes", None))
        self.pushButton_clip_nuke_2.setText(QCoreApplication.translate("Form", u"IMPORT", None))
        self.groupBox_clip_comment_3.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_82.setText("")
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_nodes), QCoreApplication.translate("Form", u"NODES", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_clip), QCoreApplication.translate("Form", u"LIB", None))
        self.groupBox_shot_file_info_3.setTitle(QCoreApplication.translate("Form", u"File information", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_35.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_36.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_37.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_38.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_39.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_pub_filename.setText("")
        self.label_pub_filetype.setText("")
        self.label_pub_framerange.setText("")
        self.label_pub_resolution.setText("")
        self.label_pub_savedtime.setText("")
        self.label_pub_filesize.setText("")
        self.pushButton_pub_publish.setText(QCoreApplication.translate("Form", u"Publish", None))
        self.groupBox_shot_comment_4.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.plainTextEdit_pub_comment.setPlainText("")
        self.groupBox_shot_comment_5.setTitle(QCoreApplication.translate("Form", u"Thumbnail", None))
        self.label_shot_comment_4.setText("")
        self.label_pub_thumbnail.setText("")
        self.label_mytask_filepath_2.setText(QCoreApplication.translate("Form", u"PUBLISH (Manager)", None))
        self.pushButton_pub_retake.setText(QCoreApplication.translate("Form", u"Retake", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_pub), QCoreApplication.translate("Form", u"PUB", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"SEQ ", None))
        self.label_username.setText("")
        self.label_rank.setText("")
        self.label_projectname.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"Project Name", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"User Name", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"Rank", None))
    # retranslateUi

