# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGridLayout,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QListWidget, QListWidgetItem, QPushButton, QSizePolicy,
    QTabWidget, QTableWidget, QTableWidgetItem, QToolBox,
    QTreeWidget, QTreeWidgetItem, QVBoxLayout, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1155, 889)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.tabWidget_all = QTabWidget(Form)
        self.tabWidget_all.setObjectName(u"tabWidget_all")
        self.tabWidget_all.setGeometry(QRect(40, 90, 1071, 761))
        font = QFont()
        font.setBold(True)
        self.tabWidget_all.setFont(font)
        self.tabWidget_all.setStyleSheet(u"")
        self.tabWidget_all.setTabPosition(QTabWidget.North)
        self.tabWidget_all.setTabShape(QTabWidget.Rounded)
        self.tabWidget_all.setUsesScrollButtons(True)
        self.tabWidget_all.setDocumentMode(False)
        self.tabWidget_all.setTabsClosable(False)
        self.tabWidget_all.setMovable(True)
        self.tabWidget_all.setTabBarAutoHide(False)
        self.tab_shot = QWidget()
        self.tab_shot.setObjectName(u"tab_shot")
        self.gridLayoutWidget = QWidget(self.tab_shot)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(290, 50, 521, 431))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_shot_task = QTabWidget(self.gridLayoutWidget)
        self.tabWidget_shot_task.setObjectName(u"tabWidget_shot_task")
        self.tabWidget_shot_task.setFont(font)
        self.tab_work = QWidget()
        self.tab_work.setObjectName(u"tab_work")
        self.tableWidget_shot_work = QTableWidget(self.tab_work)
        self.tableWidget_shot_work.setObjectName(u"tableWidget_shot_work")
        self.tableWidget_shot_work.setGeometry(QRect(10, 10, 496, 378))
        self.tabWidget_shot_task.addTab(self.tab_work, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tableWidget_shot_mov = QTableWidget(self.tab_5)
        self.tableWidget_shot_mov.setObjectName(u"tableWidget_shot_mov")
        self.tableWidget_shot_mov.setGeometry(QRect(10, 10, 496, 378))
        self.tabWidget_shot_task.addTab(self.tab_5, "")
        self.tab_exr = QWidget()
        self.tab_exr.setObjectName(u"tab_exr")
        self.tableWidget_shot_exr = QTableWidget(self.tab_exr)
        self.tableWidget_shot_exr.setObjectName(u"tableWidget_shot_exr")
        self.tableWidget_shot_exr.setGeometry(QRect(10, 10, 496, 378))
        self.tabWidget_shot_task.addTab(self.tab_exr, "")

        self.gridLayout.addWidget(self.tabWidget_shot_task, 0, 1, 1, 1)

        self.horizontalLayoutWidget = QWidget(self.tab_shot)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 221, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setBold(False)
        self.label.setFont(font1)

        self.horizontalLayout.addWidget(self.label)

        self.comboBox_shot_shotname = QComboBox(self.horizontalLayoutWidget)
        self.comboBox_shot_shotname.setObjectName(u"comboBox_shot_shotname")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.comboBox_shot_shotname.sizePolicy().hasHeightForWidth())
        self.comboBox_shot_shotname.setSizePolicy(sizePolicy2)

        self.horizontalLayout.addWidget(self.comboBox_shot_shotname)

        self.label_shot_filepath = QLabel(self.tab_shot)
        self.label_shot_filepath.setObjectName(u"label_shot_filepath")
        self.label_shot_filepath.setGeometry(QRect(290, 20, 521, 19))
        self.groupBox_shot_comment = QGroupBox(self.tab_shot)
        self.groupBox_shot_comment.setObjectName(u"groupBox_shot_comment")
        self.groupBox_shot_comment.setGeometry(QRect(820, 250, 231, 181))
        font2 = QFont()
        font2.setBold(True)
        font2.setUnderline(False)
        font2.setStrikeOut(False)
        self.groupBox_shot_comment.setFont(font2)
        self.groupBox_shot_comment.setFlat(False)
        self.groupBox_shot_comment.setCheckable(False)
        self.label_shot_comment = QLabel(self.groupBox_shot_comment)
        self.label_shot_comment.setObjectName(u"label_shot_comment")
        self.label_shot_comment.setGeometry(QRect(10, 30, 211, 141))
        self.tabWidget_shot_status = QTabWidget(self.tab_shot)
        self.tabWidget_shot_status.setObjectName(u"tabWidget_shot_status")
        self.tabWidget_shot_status.setGeometry(QRect(10, 490, 1041, 221))
        self.tabWidget_shot_status.setUsesScrollButtons(True)
        self.tabWidget_shot_status.setDocumentMode(True)
        self.tabWidget_shot_status.setTabsClosable(False)
        self.tabWidget_shot_status.setMovable(True)
        self.tabWidget_shot_status.setTabBarAutoHide(False)
        self.tab_shot_mm = QWidget()
        self.tab_shot_mm.setObjectName(u"tab_shot_mm")
        self.tabWidget_shot_status.addTab(self.tab_shot_mm, "")
        self.tab_shot_ldv = QWidget()
        self.tab_shot_ldv.setObjectName(u"tab_shot_ldv")
        self.tabWidget_shot_status.addTab(self.tab_shot_ldv, "")
        self.tab_shot_lit = QWidget()
        self.tab_shot_lit.setObjectName(u"tab_shot_lit")
        self.tabWidget_shot_status.addTab(self.tab_shot_lit, "")
        self.tab_shot_fx = QWidget()
        self.tab_shot_fx.setObjectName(u"tab_shot_fx")
        self.tabWidget_shot_status.addTab(self.tab_shot_fx, "")
        self.tab_shot_comp = QWidget()
        self.tab_shot_comp.setObjectName(u"tab_shot_comp")
        self.tabWidget_shot_status.addTab(self.tab_shot_comp, "")
        self.groupBox_shot_file_info = QGroupBox(self.tab_shot)
        self.groupBox_shot_file_info.setObjectName(u"groupBox_shot_file_info")
        self.groupBox_shot_file_info.setGeometry(QRect(820, 50, 231, 191))
        self.groupBox_shot_file_info.setFont(font2)
        self.groupBox_shot_file_info.setFlat(False)
        self.groupBox_shot_file_info.setCheckable(False)
        self.verticalLayoutWidget = QWidget(self.groupBox_shot_file_info)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 30, 80, 151))
        self.verticalLayout_3 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_16 = QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName(u"label_16")
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(False)
        font3.setUnderline(False)
        font3.setStrikeOut(False)
        self.label_16.setFont(font3)

        self.verticalLayout_3.addWidget(self.label_16)

        self.label_14 = QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setFont(font3)

        self.verticalLayout_3.addWidget(self.label_14)

        self.label_10 = QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font3)

        self.verticalLayout_3.addWidget(self.label_10)

        self.label_6 = QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font3)

        self.verticalLayout_3.addWidget(self.label_6)

        self.label_9 = QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font3)

        self.verticalLayout_3.addWidget(self.label_9)

        self.label_20 = QLabel(self.verticalLayoutWidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setFont(font3)

        self.verticalLayout_3.addWidget(self.label_20)

        self.verticalLayoutWidget_2 = QWidget(self.groupBox_shot_file_info)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(100, 30, 121, 151))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_shot_filename = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filename.setObjectName(u"label_shot_filename")
        self.label_shot_filename.setFont(font3)

        self.verticalLayout_4.addWidget(self.label_shot_filename)

        self.label_shot_filetype = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filetype.setObjectName(u"label_shot_filetype")
        self.label_shot_filetype.setFont(font3)

        self.verticalLayout_4.addWidget(self.label_shot_filetype)

        self.label_shot_framerange = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_framerange.setObjectName(u"label_shot_framerange")
        self.label_shot_framerange.setFont(font3)

        self.verticalLayout_4.addWidget(self.label_shot_framerange)

        self.label_shot_resolution = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_resolution.setObjectName(u"label_shot_resolution")
        self.label_shot_resolution.setFont(font3)

        self.verticalLayout_4.addWidget(self.label_shot_resolution)

        self.label_shot_savedtime = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_savedtime.setObjectName(u"label_shot_savedtime")
        self.label_shot_savedtime.setFont(font3)

        self.verticalLayout_4.addWidget(self.label_shot_savedtime)

        self.label_shot_filesize = QLabel(self.verticalLayoutWidget_2)
        self.label_shot_filesize.setObjectName(u"label_shot_filesize")
        self.label_shot_filesize.setFont(font3)

        self.verticalLayout_4.addWidget(self.label_shot_filesize)

        self.pushButton_shot_nuke = QPushButton(self.tab_shot)
        self.pushButton_shot_nuke.setObjectName(u"pushButton_shot_nuke")
        self.pushButton_shot_nuke.setGeometry(QRect(820, 440, 231, 41))
        self.tableWidget_shot_file_struc = QTableWidget(self.tab_shot)
        self.tableWidget_shot_file_struc.setObjectName(u"tableWidget_shot_file_struc")
        self.tableWidget_shot_file_struc.setGeometry(QRect(10, 50, 271, 431))
        self.tabWidget_all.addTab(self.tab_shot, "")
        self.tab_my_task = QWidget()
        self.tab_my_task.setObjectName(u"tab_my_task")
        self.horizontalLayoutWidget_4 = QWidget(self.tab_my_task)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(10, 10, 221, 41))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.horizontalLayoutWidget_4)
        self.label_12.setObjectName(u"label_12")
        sizePolicy1.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy1)
        self.label_12.setFont(font1)

        self.horizontalLayout_5.addWidget(self.label_12)

        self.comboBox_mytask_shotname = QComboBox(self.horizontalLayoutWidget_4)
        self.comboBox_mytask_shotname.setObjectName(u"comboBox_mytask_shotname")
        sizePolicy2.setHeightForWidth(self.comboBox_mytask_shotname.sizePolicy().hasHeightForWidth())
        self.comboBox_mytask_shotname.setSizePolicy(sizePolicy2)

        self.horizontalLayout_5.addWidget(self.comboBox_mytask_shotname)

        self.treeWidget_mytask_file_sturc = QTreeWidget(self.tab_my_task)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setText(0, u"1");
        self.treeWidget_mytask_file_sturc.setHeaderItem(__qtreewidgetitem)
        self.treeWidget_mytask_file_sturc.setObjectName(u"treeWidget_mytask_file_sturc")
        self.treeWidget_mytask_file_sturc.setGeometry(QRect(10, 50, 271, 431))
        self.tabWidget_mytask_status = QTabWidget(self.tab_my_task)
        self.tabWidget_mytask_status.setObjectName(u"tabWidget_mytask_status")
        self.tabWidget_mytask_status.setGeometry(QRect(10, 490, 1041, 221))
        self.tabWidget_mytask_status.setUsesScrollButtons(True)
        self.tabWidget_mytask_status.setDocumentMode(True)
        self.tabWidget_mytask_status.setTabsClosable(False)
        self.tabWidget_mytask_status.setMovable(True)
        self.tabWidget_mytask_status.setTabBarAutoHide(False)
        self.tab_mt_mm = QWidget()
        self.tab_mt_mm.setObjectName(u"tab_mt_mm")
        self.tabWidget_mytask_status.addTab(self.tab_mt_mm, "")
        self.tab_mt_ldv = QWidget()
        self.tab_mt_ldv.setObjectName(u"tab_mt_ldv")
        self.tabWidget_mytask_status.addTab(self.tab_mt_ldv, "")
        self.tab_mt_lit = QWidget()
        self.tab_mt_lit.setObjectName(u"tab_mt_lit")
        self.tabWidget_mytask_status.addTab(self.tab_mt_lit, "")
        self.tab_mt_fx = QWidget()
        self.tab_mt_fx.setObjectName(u"tab_mt_fx")
        self.tabWidget_mytask_status.addTab(self.tab_mt_fx, "")
        self.tab_mt_comp = QWidget()
        self.tab_mt_comp.setObjectName(u"tab_mt_comp")
        self.tabWidget_mytask_status.addTab(self.tab_mt_comp, "")
        self.tableWidget = QTableWidget(self.tab_my_task)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(290, 50, 521, 431))
        self.groupBox_shot_comment_2 = QGroupBox(self.tab_my_task)
        self.groupBox_shot_comment_2.setObjectName(u"groupBox_shot_comment_2")
        self.groupBox_shot_comment_2.setGeometry(QRect(820, 250, 231, 181))
        self.groupBox_shot_comment_2.setFont(font2)
        self.groupBox_shot_comment_2.setFlat(False)
        self.groupBox_shot_comment_2.setCheckable(False)
        self.label_shot_comment_2 = QLabel(self.groupBox_shot_comment_2)
        self.label_shot_comment_2.setObjectName(u"label_shot_comment_2")
        self.label_shot_comment_2.setGeometry(QRect(10, 30, 211, 141))
        self.pushButton_shot_nuke_2 = QPushButton(self.tab_my_task)
        self.pushButton_shot_nuke_2.setObjectName(u"pushButton_shot_nuke_2")
        self.pushButton_shot_nuke_2.setGeometry(QRect(820, 440, 231, 41))
        self.label_mytask_filepath = QLabel(self.tab_my_task)
        self.label_mytask_filepath.setObjectName(u"label_mytask_filepath")
        self.label_mytask_filepath.setGeometry(QRect(290, 20, 521, 19))
        self.tabWidget_all.addTab(self.tab_my_task, "")
        self.tab_clip = QWidget()
        self.tab_clip.setObjectName(u"tab_clip")
        self.gridLayoutWidget_2 = QWidget(self.tab_clip)
        self.gridLayoutWidget_2.setObjectName(u"gridLayoutWidget_2")
        self.gridLayoutWidget_2.setGeometry(QRect(290, 10, 771, 701))
        self.gridLayout_3 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.tabWidget_template = QTabWidget(self.gridLayoutWidget_2)
        self.tabWidget_template.setObjectName(u"tabWidget_template")
        self.tabWidget_template.setFont(font)
        self.tab_asset = QWidget()
        self.tab_asset.setObjectName(u"tab_asset")
        self.pushButton_asset_nuke = QPushButton(self.tab_asset)
        self.pushButton_asset_nuke.setObjectName(u"pushButton_asset_nuke")
        self.pushButton_asset_nuke.setGeometry(QRect(520, 610, 231, 41))
        self.groupBox_asset_comment = QGroupBox(self.tab_asset)
        self.groupBox_asset_comment.setObjectName(u"groupBox_asset_comment")
        self.groupBox_asset_comment.setGeometry(QRect(520, 420, 231, 181))
        self.groupBox_asset_comment.setFont(font2)
        self.groupBox_asset_comment.setFlat(False)
        self.groupBox_asset_comment.setCheckable(False)
        self.label_asset_comment = QLabel(self.groupBox_asset_comment)
        self.label_asset_comment.setObjectName(u"label_asset_comment")
        self.label_asset_comment.setGeometry(QRect(10, 30, 211, 141))
        self.groupBox_asset_file_info = QGroupBox(self.tab_asset)
        self.groupBox_asset_file_info.setObjectName(u"groupBox_asset_file_info")
        self.groupBox_asset_file_info.setGeometry(QRect(520, 10, 231, 401))
        self.groupBox_asset_file_info.setFont(font2)
        self.groupBox_asset_file_info.setFlat(False)
        self.groupBox_asset_file_info.setCheckable(False)
        self.verticalLayoutWidget_5 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(10, 30, 80, 151))
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_23 = QLabel(self.verticalLayoutWidget_5)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setFont(font3)

        self.verticalLayout_7.addWidget(self.label_23)

        self.label_24 = QLabel(self.verticalLayoutWidget_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setFont(font3)

        self.verticalLayout_7.addWidget(self.label_24)

        self.label_25 = QLabel(self.verticalLayoutWidget_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setFont(font3)

        self.verticalLayout_7.addWidget(self.label_25)

        self.label_26 = QLabel(self.verticalLayoutWidget_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setFont(font3)

        self.verticalLayout_7.addWidget(self.label_26)

        self.label_27 = QLabel(self.verticalLayoutWidget_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setFont(font3)

        self.verticalLayout_7.addWidget(self.label_27)

        self.label_28 = QLabel(self.verticalLayoutWidget_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setFont(font3)

        self.verticalLayout_7.addWidget(self.label_28)

        self.verticalLayoutWidget_6 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(100, 30, 121, 151))
        self.verticalLayout_8 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_asset_filename = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filename.setObjectName(u"label_asset_filename")
        self.label_asset_filename.setFont(font3)

        self.verticalLayout_8.addWidget(self.label_asset_filename)

        self.label_asset_filetype = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filetype.setObjectName(u"label_asset_filetype")
        self.label_asset_filetype.setFont(font3)

        self.verticalLayout_8.addWidget(self.label_asset_filetype)

        self.label_asset_framerange = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_framerange.setObjectName(u"label_asset_framerange")
        self.label_asset_framerange.setFont(font3)

        self.verticalLayout_8.addWidget(self.label_asset_framerange)

        self.label_asset_resolution = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_resolution.setObjectName(u"label_asset_resolution")
        self.label_asset_resolution.setFont(font3)

        self.verticalLayout_8.addWidget(self.label_asset_resolution)

        self.label_asset_savedtime = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_savedtime.setObjectName(u"label_asset_savedtime")
        self.label_asset_savedtime.setFont(font3)

        self.verticalLayout_8.addWidget(self.label_asset_savedtime)

        self.label_asset_filesize = QLabel(self.verticalLayoutWidget_6)
        self.label_asset_filesize.setObjectName(u"label_asset_filesize")
        self.label_asset_filesize.setFont(font3)

        self.verticalLayout_8.addWidget(self.label_asset_filesize)

        self.line = QFrame(self.groupBox_asset_file_info)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 175, 231, 31))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.verticalLayoutWidget_11 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_11.setObjectName(u"verticalLayoutWidget_11")
        self.verticalLayoutWidget_11.setGeometry(QRect(10, 200, 80, 42))
        self.verticalLayout_13 = QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.label_47 = QLabel(self.verticalLayoutWidget_11)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setFont(font3)

        self.verticalLayout_13.addWidget(self.label_47)

        self.label_48 = QLabel(self.verticalLayoutWidget_11)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setFont(font3)

        self.verticalLayout_13.addWidget(self.label_48)

        self.verticalLayoutWidget_12 = QWidget(self.groupBox_asset_file_info)
        self.verticalLayoutWidget_12.setObjectName(u"verticalLayoutWidget_12")
        self.verticalLayoutWidget_12.setGeometry(QRect(100, 200, 121, 42))
        self.verticalLayout_14 = QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.label_asset_version = QLabel(self.verticalLayoutWidget_12)
        self.label_asset_version.setObjectName(u"label_asset_version")
        self.label_asset_version.setFont(font3)

        self.verticalLayout_14.addWidget(self.label_asset_version)

        self.label_asset_pubdate = QLabel(self.verticalLayoutWidget_12)
        self.label_asset_pubdate.setObjectName(u"label_asset_pubdate")
        self.label_asset_pubdate.setFont(font3)

        self.verticalLayout_14.addWidget(self.label_asset_pubdate)

        self.toolBox_asset_task = QToolBox(self.tab_asset)
        self.toolBox_asset_task.setObjectName(u"toolBox_asset_task")
        self.toolBox_asset_task.setGeometry(QRect(10, 57, 501, 591))
        self.toolBox_asset_task.setFont(font)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.page_5.setGeometry(QRect(0, 0, 501, 525))
        self.tableWidget_asset_mdl_asset = QTableWidget(self.page_5)
        self.tableWidget_asset_mdl_asset.setObjectName(u"tableWidget_asset_mdl_asset")
        self.tableWidget_asset_mdl_asset.setGeometry(QRect(0, 0, 501, 525))
        self.toolBox_asset_task.addItem(self.page_5, u"MDL")
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.page_6.setGeometry(QRect(0, 0, 501, 525))
        self.tableWidget_asset_ani_asset = QTableWidget(self.page_6)
        self.tableWidget_asset_ani_asset.setObjectName(u"tableWidget_asset_ani_asset")
        self.tableWidget_asset_ani_asset.setGeometry(QRect(0, 1, 501, 524))
        self.toolBox_asset_task.addItem(self.page_6, u"ANI")
        self.horizontalLayoutWidget_8 = QWidget(self.tab_asset)
        self.horizontalLayoutWidget_8.setObjectName(u"horizontalLayoutWidget_8")
        self.horizontalLayoutWidget_8.setGeometry(QRect(10, 10, 241, 41))
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_29 = QLabel(self.horizontalLayoutWidget_8)
        self.label_29.setObjectName(u"label_29")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy3)
        self.label_29.setFont(font)

        self.horizontalLayout_8.addWidget(self.label_29)

        self.comboBox_asset_assettype = QComboBox(self.horizontalLayoutWidget_8)
        self.comboBox_asset_assettype.setObjectName(u"comboBox_asset_assettype")

        self.horizontalLayout_8.addWidget(self.comboBox_asset_assettype)

        self.tabWidget_template.addTab(self.tab_asset, "")
        self.tab_clip1 = QWidget()
        self.tab_clip1.setObjectName(u"tab_clip1")
        self.groupBox_asset_file_info_2 = QGroupBox(self.tab_clip1)
        self.groupBox_asset_file_info_2.setObjectName(u"groupBox_asset_file_info_2")
        self.groupBox_asset_file_info_2.setGeometry(QRect(520, 10, 231, 401))
        self.groupBox_asset_file_info_2.setFont(font2)
        self.groupBox_asset_file_info_2.setFlat(False)
        self.groupBox_asset_file_info_2.setCheckable(False)
        self.verticalLayoutWidget_13 = QWidget(self.groupBox_asset_file_info_2)
        self.verticalLayoutWidget_13.setObjectName(u"verticalLayoutWidget_13")
        self.verticalLayoutWidget_13.setGeometry(QRect(10, 30, 80, 151))
        self.verticalLayout_15 = QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.label_51 = QLabel(self.verticalLayoutWidget_13)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setFont(font3)

        self.verticalLayout_15.addWidget(self.label_51)

        self.label_52 = QLabel(self.verticalLayoutWidget_13)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setFont(font3)

        self.verticalLayout_15.addWidget(self.label_52)

        self.label_53 = QLabel(self.verticalLayoutWidget_13)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setFont(font3)

        self.verticalLayout_15.addWidget(self.label_53)

        self.label_54 = QLabel(self.verticalLayoutWidget_13)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setFont(font3)

        self.verticalLayout_15.addWidget(self.label_54)

        self.label_55 = QLabel(self.verticalLayoutWidget_13)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setFont(font3)

        self.verticalLayout_15.addWidget(self.label_55)

        self.label_56 = QLabel(self.verticalLayoutWidget_13)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setFont(font3)

        self.verticalLayout_15.addWidget(self.label_56)

        self.verticalLayoutWidget_14 = QWidget(self.groupBox_asset_file_info_2)
        self.verticalLayoutWidget_14.setObjectName(u"verticalLayoutWidget_14")
        self.verticalLayoutWidget_14.setGeometry(QRect(100, 30, 121, 151))
        self.verticalLayout_16 = QVBoxLayout(self.verticalLayoutWidget_14)
        self.verticalLayout_16.setObjectName(u"verticalLayout_16")
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.label_clip_filename = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filename.setObjectName(u"label_clip_filename")
        self.label_clip_filename.setFont(font3)

        self.verticalLayout_16.addWidget(self.label_clip_filename)

        self.label_clip_filetype = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filetype.setObjectName(u"label_clip_filetype")
        self.label_clip_filetype.setFont(font3)

        self.verticalLayout_16.addWidget(self.label_clip_filetype)

        self.label_clip_framerange = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_framerange.setObjectName(u"label_clip_framerange")
        self.label_clip_framerange.setFont(font3)

        self.verticalLayout_16.addWidget(self.label_clip_framerange)

        self.label_clip_resolution = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_resolution.setObjectName(u"label_clip_resolution")
        self.label_clip_resolution.setFont(font3)

        self.verticalLayout_16.addWidget(self.label_clip_resolution)

        self.label_clip_savedtime = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_savedtime.setObjectName(u"label_clip_savedtime")
        self.label_clip_savedtime.setFont(font3)

        self.verticalLayout_16.addWidget(self.label_clip_savedtime)

        self.label_clip_filesize = QLabel(self.verticalLayoutWidget_14)
        self.label_clip_filesize.setObjectName(u"label_clip_filesize")
        self.label_clip_filesize.setFont(font3)

        self.verticalLayout_16.addWidget(self.label_clip_filesize)

        self.pushButton_clip_nuke = QPushButton(self.tab_clip1)
        self.pushButton_clip_nuke.setObjectName(u"pushButton_clip_nuke")
        self.pushButton_clip_nuke.setGeometry(QRect(520, 610, 231, 41))
        self.groupBox_clip_comment = QGroupBox(self.tab_clip1)
        self.groupBox_clip_comment.setObjectName(u"groupBox_clip_comment")
        self.groupBox_clip_comment.setGeometry(QRect(520, 420, 231, 181))
        self.groupBox_clip_comment.setFont(font2)
        self.groupBox_clip_comment.setFlat(False)
        self.groupBox_clip_comment.setCheckable(False)
        self.label_clip_comment = QLabel(self.groupBox_clip_comment)
        self.label_clip_comment.setObjectName(u"label_clip_comment")
        self.label_clip_comment.setGeometry(QRect(10, 30, 211, 141))
        font4 = QFont()
        font4.setBold(False)
        font4.setUnderline(False)
        font4.setStrikeOut(False)
        self.label_clip_comment.setFont(font4)
        self.tableWidget_clip_files = QTableWidget(self.tab_clip1)
        self.tableWidget_clip_files.setObjectName(u"tableWidget_clip_files")
        self.tableWidget_clip_files.setGeometry(QRect(10, 10, 501, 641))
        self.tabWidget_template.addTab(self.tab_clip1, "")
        self.tab_nodes = QWidget()
        self.tab_nodes.setObjectName(u"tab_nodes")
        self.groupBox_nodes_file_info = QGroupBox(self.tab_nodes)
        self.groupBox_nodes_file_info.setObjectName(u"groupBox_nodes_file_info")
        self.groupBox_nodes_file_info.setGeometry(QRect(520, 10, 231, 401))
        self.groupBox_nodes_file_info.setFont(font2)
        self.groupBox_nodes_file_info.setFlat(False)
        self.groupBox_nodes_file_info.setCheckable(False)
        self.verticalLayoutWidget_21 = QWidget(self.groupBox_nodes_file_info)
        self.verticalLayoutWidget_21.setObjectName(u"verticalLayoutWidget_21")
        self.verticalLayoutWidget_21.setGeometry(QRect(10, 30, 80, 151))
        self.verticalLayout_23 = QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_23.setObjectName(u"verticalLayout_23")
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.label_59 = QLabel(self.verticalLayoutWidget_21)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setFont(font3)

        self.verticalLayout_23.addWidget(self.label_59)

        self.label_60 = QLabel(self.verticalLayoutWidget_21)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setFont(font3)

        self.verticalLayout_23.addWidget(self.label_60)

        self.label_75 = QLabel(self.verticalLayoutWidget_21)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setFont(font3)

        self.verticalLayout_23.addWidget(self.label_75)

        self.label_76 = QLabel(self.verticalLayoutWidget_21)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setFont(font3)

        self.verticalLayout_23.addWidget(self.label_76)

        self.label_77 = QLabel(self.verticalLayoutWidget_21)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setFont(font3)

        self.verticalLayout_23.addWidget(self.label_77)

        self.label_78 = QLabel(self.verticalLayoutWidget_21)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setFont(font3)

        self.verticalLayout_23.addWidget(self.label_78)

        self.verticalLayoutWidget_22 = QWidget(self.groupBox_nodes_file_info)
        self.verticalLayoutWidget_22.setObjectName(u"verticalLayoutWidget_22")
        self.verticalLayoutWidget_22.setGeometry(QRect(100, 30, 121, 151))
        self.verticalLayout_24 = QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_24.setObjectName(u"verticalLayout_24")
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.label_nodes_filename = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_filename.setObjectName(u"label_nodes_filename")
        self.label_nodes_filename.setFont(font3)

        self.verticalLayout_24.addWidget(self.label_nodes_filename)

        self.label_nodes_filetype = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_filetype.setObjectName(u"label_nodes_filetype")
        self.label_nodes_filetype.setFont(font3)

        self.verticalLayout_24.addWidget(self.label_nodes_filetype)

        self.label_nodes_framerange = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_framerange.setObjectName(u"label_nodes_framerange")
        self.label_nodes_framerange.setFont(font3)

        self.verticalLayout_24.addWidget(self.label_nodes_framerange)

        self.label_nodes_resolution = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_resolution.setObjectName(u"label_nodes_resolution")
        self.label_nodes_resolution.setFont(font3)

        self.verticalLayout_24.addWidget(self.label_nodes_resolution)

        self.label_nodes_savedtime = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_savedtime.setObjectName(u"label_nodes_savedtime")
        self.label_nodes_savedtime.setFont(font3)

        self.verticalLayout_24.addWidget(self.label_nodes_savedtime)

        self.label_nodes_filesize = QLabel(self.verticalLayoutWidget_22)
        self.label_nodes_filesize.setObjectName(u"label_nodes_filesize")
        self.label_nodes_filesize.setFont(font3)

        self.verticalLayout_24.addWidget(self.label_nodes_filesize)

        self.line_4 = QFrame(self.groupBox_nodes_file_info)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(0, 175, 231, 31))
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.listWidget_nodes_info = QListWidget(self.groupBox_nodes_file_info)
        self.listWidget_nodes_info.setObjectName(u"listWidget_nodes_info")
        self.listWidget_nodes_info.setGeometry(QRect(10, 221, 211, 171))
        self.label_49 = QLabel(self.groupBox_nodes_file_info)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(10, 200, 63, 19))
        self.pushButton_clip_nuke_2 = QPushButton(self.tab_nodes)
        self.pushButton_clip_nuke_2.setObjectName(u"pushButton_clip_nuke_2")
        self.pushButton_clip_nuke_2.setGeometry(QRect(520, 610, 231, 41))
        self.groupBox_clip_comment_3 = QGroupBox(self.tab_nodes)
        self.groupBox_clip_comment_3.setObjectName(u"groupBox_clip_comment_3")
        self.groupBox_clip_comment_3.setGeometry(QRect(520, 420, 231, 181))
        self.groupBox_clip_comment_3.setFont(font2)
        self.groupBox_clip_comment_3.setFlat(False)
        self.groupBox_clip_comment_3.setCheckable(False)
        self.label_82 = QLabel(self.groupBox_clip_comment_3)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(10, 30, 211, 141))
        self.label_82.setFont(font4)
        self.tableWidget_nodes_files = QTableWidget(self.tab_nodes)
        self.tableWidget_nodes_files.setObjectName(u"tableWidget_nodes_files")
        self.tableWidget_nodes_files.setGeometry(QRect(10, 10, 501, 641))
        self.tabWidget_template.addTab(self.tab_nodes, "")

        self.gridLayout_3.addWidget(self.tabWidget_template, 0, 0, 1, 1)

        self.horizontalLayoutWidget_3 = QWidget(self.tab_clip)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(10, 10, 221, 41))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.horizontalLayoutWidget_3)
        self.label_5.setObjectName(u"label_5")
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setFont(font1)

        self.horizontalLayout_3.addWidget(self.label_5)

        self.comboBox_clip_shotname = QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox_clip_shotname.setObjectName(u"comboBox_clip_shotname")
        sizePolicy2.setHeightForWidth(self.comboBox_clip_shotname.sizePolicy().hasHeightForWidth())
        self.comboBox_clip_shotname.setSizePolicy(sizePolicy2)

        self.horizontalLayout_3.addWidget(self.comboBox_clip_shotname)

        self.treeWidget_lib_file_sturc = QTreeWidget(self.tab_clip)
        __qtreewidgetitem1 = QTreeWidgetItem()
        __qtreewidgetitem1.setText(0, u"1");
        self.treeWidget_lib_file_sturc.setHeaderItem(__qtreewidgetitem1)
        self.treeWidget_lib_file_sturc.setObjectName(u"treeWidget_lib_file_sturc")
        self.treeWidget_lib_file_sturc.setGeometry(QRect(10, 50, 271, 661))
        self.tabWidget_all.addTab(self.tab_clip, "")
        self.horizontalLayoutWidget_2 = QWidget(Form)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(50, 30, 191, 51))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(u"label_3")
        sizePolicy1.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy1)
        self.label_3.setFont(font1)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.comboBox_seq = QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_seq.setObjectName(u"comboBox_seq")

        self.horizontalLayout_2.addWidget(self.comboBox_seq)

        self.gridLayoutWidget_3 = QWidget(Form)
        self.gridLayoutWidget_3.setObjectName(u"gridLayoutWidget_3")
        self.gridLayoutWidget_3.setGeometry(QRect(900, 59, 211, 51))
        self.gridLayout_4 = QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(u"label_7")
        sizePolicy3.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy3)
        font5 = QFont()
        font5.setPointSize(8)
        font5.setBold(True)
        self.label_7.setFont(font5)

        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)

        self.frame = QFrame(self.gridLayoutWidget_3)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_username = QLabel(self.frame)
        self.label_username.setObjectName(u"label_username")
        self.label_username.setGeometry(QRect(5, 1, 151, 20))
        font6 = QFont()
        font6.setPointSize(8)
        self.label_username.setFont(font6)

        self.gridLayout_4.addWidget(self.frame, 0, 1, 1, 1)

        self.label_8 = QLabel(self.gridLayoutWidget_3)
        self.label_8.setObjectName(u"label_8")
        sizePolicy3.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy3)
        self.label_8.setFont(font5)

        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)

        self.frame_2 = QFrame(self.gridLayoutWidget_3)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_projectname = QLabel(self.frame_2)
        self.label_projectname.setObjectName(u"label_projectname")
        self.label_projectname.setGeometry(QRect(5, 0, 151, 21))
        self.label_projectname.setFont(font6)

        self.gridLayout_4.addWidget(self.frame_2, 1, 1, 1, 1)


        self.retranslateUi(Form)

        self.tabWidget_all.setCurrentIndex(1)
        self.tabWidget_shot_task.setCurrentIndex(0)
        self.tabWidget_shot_status.setCurrentIndex(0)
        self.tabWidget_mytask_status.setCurrentIndex(4)
        self.tabWidget_template.setCurrentIndex(1)
        self.toolBox_asset_task.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_work), QCoreApplication.translate("Form", u"WORK", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_5), QCoreApplication.translate("Form", u"MOV", None))
        self.tabWidget_shot_task.setTabText(self.tabWidget_shot_task.indexOf(self.tab_exr), QCoreApplication.translate("Form", u"EXR", None))
        self.label.setText(QCoreApplication.translate("Form", u" shot code ", None))
        self.label_shot_filepath.setText(QCoreApplication.translate("Form", u"Task Name > File Path", None))
        self.groupBox_shot_comment.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_shot_comment.setText("")
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_mm), QCoreApplication.translate("Form", u"MM", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_ldv), QCoreApplication.translate("Form", u"LDV", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_lit), QCoreApplication.translate("Form", u"LIT", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_fx), QCoreApplication.translate("Form", u"FX", None))
        self.tabWidget_shot_status.setTabText(self.tabWidget_shot_status.indexOf(self.tab_shot_comp), QCoreApplication.translate("Form", u"COMP", None))
        self.groupBox_shot_file_info.setTitle(QCoreApplication.translate("Form", u"File information", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_shot_filename.setText("")
        self.label_shot_filetype.setText("")
        self.label_shot_framerange.setText("")
        self.label_shot_resolution.setText("")
        self.label_shot_savedtime.setText("")
        self.label_shot_filesize.setText("")
        self.pushButton_shot_nuke.setText(QCoreApplication.translate("Form", u"NUKE", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_shot), QCoreApplication.translate("Form", u"SHOT", None))
        self.label_12.setText(QCoreApplication.translate("Form", u" shot code ", None))
        self.tabWidget_mytask_status.setTabText(self.tabWidget_mytask_status.indexOf(self.tab_mt_mm), QCoreApplication.translate("Form", u"MM", None))
        self.tabWidget_mytask_status.setTabText(self.tabWidget_mytask_status.indexOf(self.tab_mt_ldv), QCoreApplication.translate("Form", u"LDV", None))
        self.tabWidget_mytask_status.setTabText(self.tabWidget_mytask_status.indexOf(self.tab_mt_lit), QCoreApplication.translate("Form", u"LIT", None))
        self.tabWidget_mytask_status.setTabText(self.tabWidget_mytask_status.indexOf(self.tab_mt_fx), QCoreApplication.translate("Form", u"FX", None))
        self.tabWidget_mytask_status.setTabText(self.tabWidget_mytask_status.indexOf(self.tab_mt_comp), QCoreApplication.translate("Form", u"COMP", None))
        self.groupBox_shot_comment_2.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_shot_comment_2.setText("")
        self.pushButton_shot_nuke_2.setText(QCoreApplication.translate("Form", u"NUKE", None))
        self.label_mytask_filepath.setText(QCoreApplication.translate("Form", u"Task Name > File Path", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_my_task), QCoreApplication.translate("Form", u"MY TASK", None))
        self.pushButton_asset_nuke.setText(QCoreApplication.translate("Form", u"IMPORT", None))
        self.groupBox_asset_comment.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_asset_comment.setText("")
        self.groupBox_asset_file_info.setTitle(QCoreApplication.translate("Form", u"Asset information", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_asset_filename.setText("")
        self.label_asset_filetype.setText("")
        self.label_asset_framerange.setText("")
        self.label_asset_resolution.setText("")
        self.label_asset_savedtime.setText("")
        self.label_asset_filesize.setText("")
        self.label_47.setText(QCoreApplication.translate("Form", u"Verison", None))
        self.label_48.setText(QCoreApplication.translate("Form", u"Pub date", None))
        self.label_asset_version.setText("")
        self.label_asset_pubdate.setText("")
        self.toolBox_asset_task.setItemText(self.toolBox_asset_task.indexOf(self.page_5), QCoreApplication.translate("Form", u"MDL", None))
        self.toolBox_asset_task.setItemText(self.toolBox_asset_task.indexOf(self.page_6), QCoreApplication.translate("Form", u"ANI", None))
        self.label_29.setText(QCoreApplication.translate("Form", u" Asset type ", None))
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_asset), QCoreApplication.translate("Form", u"ASSET (cache)", None))
        self.groupBox_asset_file_info_2.setTitle(QCoreApplication.translate("Form", u"Clip information", None))
        self.label_51.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_52.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_53.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_54.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_55.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_56.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_clip_filename.setText("")
        self.label_clip_filetype.setText("")
        self.label_clip_framerange.setText("")
        self.label_clip_resolution.setText("")
        self.label_clip_savedtime.setText("")
        self.label_clip_filesize.setText("")
        self.pushButton_clip_nuke.setText(QCoreApplication.translate("Form", u"IMPORT", None))
        self.groupBox_clip_comment.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_clip_comment.setText("")
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_clip1), QCoreApplication.translate("Form", u"CLIP", None))
        self.groupBox_nodes_file_info.setTitle(QCoreApplication.translate("Form", u"File information", None))
        self.label_59.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_60.setText(QCoreApplication.translate("Form", u"File type", None))
        self.label_75.setText(QCoreApplication.translate("Form", u"Frame Range ", None))
        self.label_76.setText(QCoreApplication.translate("Form", u"Resolution", None))
        self.label_77.setText(QCoreApplication.translate("Form", u"Saved time", None))
        self.label_78.setText(QCoreApplication.translate("Form", u"File size", None))
        self.label_nodes_filename.setText("")
        self.label_nodes_filetype.setText("")
        self.label_nodes_framerange.setText("")
        self.label_nodes_resolution.setText("")
        self.label_nodes_savedtime.setText("")
        self.label_nodes_filesize.setText("")
        self.label_49.setText(QCoreApplication.translate("Form", u"Nodes", None))
        self.pushButton_clip_nuke_2.setText(QCoreApplication.translate("Form", u"IMPORT", None))
        self.groupBox_clip_comment_3.setTitle(QCoreApplication.translate("Form", u"Comment", None))
        self.label_82.setText("")
        self.tabWidget_template.setTabText(self.tabWidget_template.indexOf(self.tab_nodes), QCoreApplication.translate("Form", u"NODES", None))
        self.label_5.setText(QCoreApplication.translate("Form", u" shot code ", None))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_clip), QCoreApplication.translate("Form", u"LIB", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"SEQ ", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"User Name", None))
        self.label_username.setText("")
        self.label_8.setText(QCoreApplication.translate("Form", u"Project Name", None))
        self.label_projectname.setText("")
    # retranslateUi

